### ISSUE TITLE
Throws error while using this plugin on demo project

### ISSUE THREAD

**Issue by gamergamesz** [Shin-NiL/Godot-Android-Admob-Plugin#1]
3.2 latest

app:compileDebugJavaWithJavac 
![Screenshot (200)](https://user-images.githubusercontent.com/13883739/64060151-807b6d80-cbe6-11e9-8a5e-bf5862557cfb.png)

**Comment by Shin-NiL** [comment]
Is it working with Godot 3.2 alpha 1?

**Comment by gamergamesz** [comment]
Not unless i remove banner section

**Comment by Shin-NiL** [comment]
Well, I'm having the same issue with 3.2 alpha 1. What exactly was your workaround?

**Comment by gamergamesz** [comment]
Well i am not a coder😅 so i just removed whole banner code wection from the java file, even making "layout = null" in banner section works.

**Comment by Shin-NiL** [comment]
They removed the public layout property. I'll send a commit tha should fix this. However, the editor is crashing now ;(

**Comment by gamergamesz** [comment]
Well i have already reported the crash and there seems to be a fix merged recently/today

**Comment by Shin-NiL** [comment]
Nice! Thanks for reporting ;)
