### ISSUE TITLE
Video Tutorial

### ISSUE THREAD

**Issue by HakanSeven12** [Shin-NiL/Godot-Android-Admob-Plugin#10]
Can you create a video totarial for new Godot users?

**Comment by Shin-NiL** [comment]
I'm afraid my english is not good enough to record a video, sorry ;(

Anyways, I've just found [this great tutorial](https://godotlearn.com/godot-3-2-how-to-integrate-google-ads-admob-for-android/) using this plugin, please check out.

**Comment by HakanSeven12** [comment]
Someone did it 🙂

https://youtu.be/GYXGmk0a5KE

**Comment by Shin-NiL** [comment]
Nice, I'll close this issue then ;)
