### ISSUE TITLE
Published game using this plugin

### ISSUE THREAD

**Issue by goodeb** [Shin-NiL/Godot-Android-Admob-Plugin#100]
**Godot version:** 3.2.2

**AdMob Plugin version:** 4.1.1

First, thanks for the good work you did developing this plugin. I used it to quickly include ads in the game I just got published. The name is "Ball Toss" and it's at the link below. 

https://play.google.com/store/apps/details?id=com.EGFABT.Ball_Toss

Hope that another example of your great plugin will help get the word out.

**Comment by Shin-NiL** [comment]
Thank you very much, the game was added to the showcase :)
