### ISSUE TITLE
Showcase: WoW Death Roll Simulator

### ISSUE THREAD

**Issue by eddex** [Shin-NiL/Godot-Android-Admob-Plugin#103]
Hi @Shin-NiL 

Two days ago I finally released my first ever app on the google play store. It includes a single, optional rewarded video ad on the game over screen where the player can chose to watch an ad to get small headstart for the next try. It would be really great if you could include it in the showcase.

- Google Play: https://play.google.com/store/apps/details?id=ch.jackfruit.deathrollsimulator
- Website: https://jackfruit.games/DeathRollSimulator

Cheers,
eddex

**Comment by Shin-NiL** [comment]
Nice! Thank you very much.
