### ISSUE TITLE
Possible dead link in the README file

### ISSUE THREAD

**Issue by antonio-turco** [Shin-NiL/Godot-Android-Admob-Plugin#107]
In the first step of the setup guide, the link to the "official documentation" is dead. When i click on it, the link brings me to a missing page of the godot documentation. I think the problem is that in the README file is reported the link to the _latest_ version of the documentation (that in this case is still not available), instead the link should point to the _stable_ documentation.
In fact the link https://docs.godotengine.org/en/stable/getting_started/workflow/export/android_custom_build.html it's working.

**Comment by Shin-NiL** [comment]
Thank you very much for reporting, fixed now :)
