### ISSUE TITLE
Used your p;lugin in my game. Thank you so much

### ISSUE THREAD

**Issue by SoloCarryGuy** [Shin-NiL/Godot-Android-Admob-Plugin#109]
Godot v3.2.2

Admob v4.0.0

Used your plug-in in my game https://play.google.com/store/apps/details?id=com.GamesForLife.ZoneCrush

Thank you so much for the effort you are putting in this plug-in and providing it free of cost to new people like me.
I will try to donate some to you once I start getting revenue from my game.

**Comment by Shin-NiL** [comment]
Thank you very much :)
