### ISSUE TITLE
Not working on godot 3.2 official

### ISSUE THREAD

**Issue by Themaker482** [Shin-NiL/Godot-Android-Admob-Plugin#11]
**3.2 official**

**Not working on the official release of godot 3.2**
Hi, I decided try the module with this final release of godot 3.2 but is not working, has anyone experienced the same probllem? I even recreated the project just to see if was something related to the beta version.

**Comment by comrade96** [comment]
Is test ad working fine?

**Comment by Themaker482** [comment]
> Is test ad working fine?

No, I also tried test ads and nothing is working

**Comment by Shin-NiL** [comment]
Did you test the demo project? Could you describe the error with more details?

**Comment by hy-pac** [comment]
I tried with the 3.2 stable and it worked just fine, have you checked if the custom build is enabled and if you put "org/godotengine/godot/GodotAdMob" on android modules?

**Comment by hy-pac** [comment]
Try printing something inside an 'if' checking if the singleton is even there, like:
func _ready():
	if Engine.has_singleton("AdMob"):
		print('it works')
	pass

**Comment by Themaker482** [comment]
ok, i will try to print and see what happens

**Comment by Themaker482** [comment]
well, i set a text that says true if has singleton and its working but there is no ad displayed

**Comment by Shin-NiL** [comment]
Does the demo project work?

**Comment by Themaker482** [comment]
the demo is not working, I tought that my project could be the problem but the demo is not showing ads, have you tried with the official release? maybe is just me who has that problem

**Comment by Themaker482** [comment]
would you share the "ca-app-pub" of one of your ad blocks to test in my project? so I will se if is a problem of the app or my admob account

**Comment by Shin-NiL** [comment]
Yes, I'm using the official 3.2 release and it's working fine.
Do you have internet connection (3G, 4G, Wifi) on your android device?

**Comment by Themaker482** [comment]
Yes I have connection, so that is wierd! I wonder if is my admob account the one that is failing

**Comment by Shin-NiL** [comment]
Use the test ids from google: https://developers.google.com/admob/android/test-ads

**Comment by Themaker482** [comment]
thats right, i totally forgot about that, i am gonna run some test

**Comment by Themaker482** [comment]
definately is my account, I have to check why but I guess that would be all guys, thanks for your help!!
