### ISSUE TITLE
Used your plugin in my published game: No Rush.

### ISSUE THREAD

**Issue by haruntrkmn** [Shin-NiL/Godot-Android-Admob-Plugin#110]
[Godot] v3.2.2

Admob v4.0.0

Thanks for creating this plugin mate, it really helped me to integrate my game with Admob.

game name: No Rush: Puzzle/Platformer Game

https://play.google.com/store/apps/details?id=org.turkmenh.norush

**Comment by Shin-NiL** [comment]
Glad to know! Thank you very much.
