### ISSUE TITLE
DeathGuy use your plugin

### ISSUE THREAD

**Issue by amdotblacksheep** [Shin-NiL/Godot-Android-Admob-Plugin#113]
**Godot version:**
3.2.3
**AdMob Plugin version:**
4.1.1
**Issue description:**
No issues, i opened this issue to inform you that my android game use your admob plugin.
You can find my game here : [link](https://play.google.com/store/apps/details?id=org.amdotblacksheep.deathguy )
Thanks for your work!

**Comment by Shin-NiL** [comment]
Thank you very much. I've added your game to the showcase :)
