### ISSUE TITLE
Funding Choices

### ISSUE THREAD

**Issue by rares45** [Shin-NiL/Godot-Android-Admob-Plugin#115]
**Godot version:** 3.2.3

**AdMob Plugin version:** 4.1.1

**Issue description:**
This is a question, not an issue. I would have created a discussion, but they are disabled.

What is the best way to implement Funding Choices (https://support.google.com/fundingchoices/answer/9180084?hl=en&ref_topic=9437573) or any other type of consent chose?

**Comment by Shin-NiL** [comment]
I've enabled the discussion, feel free to use it :)
