### ISSUE TITLE
Question about license 

### ISSUE THREAD

**Issue by player910** [Shin-NiL/Godot-Android-Admob-Plugin#121]
Godot version:3.2.3

AdMob Plugin version:4.1.1

  Hello, is there any problem to use admob-lib/icon.png in my resource folder (for copyright issues) or can I delete this icon ? If I delete this icon, will the code works properly ?

**Comment by Shin-NiL** [comment]
I think it still work without the icon, but your safest option is just use a blank png with the same name and dimension.

**Comment by player910** [comment]
Thanks a lot for your reply
