### ISSUE TITLE
Used this plugin to create Domino Trail

### ISSUE THREAD

**Issue by LosykGames** [Shin-NiL/Godot-Android-Admob-Plugin#122]
Hey!
Thank you so much for the good work! Plugin works perfectly in my android game.

Game name: Domino Trail
Google Play link: https://play.google.com/store/apps/details?id=org.losyk.dominotrail

BTW, I had an issue with real ads not showing (erroe code 3) - turns out your admob account has to be verified (wasn't clear to me at the time). And to do that you have to visit AdSense and input your billing address - at least after doing that I received a confirmation email. Hope it shines more light on the problem many people have, since this detail is almost never mentioned and I feel someone might be looking for the solution in the wrong place (as I did).

**Comment by Shin-NiL** [comment]
Beautiful game, just added to the showcase.

> BTW, I had an issue with real ads not showing (erroe code 3) - turns out your admob account has to be verified (wasn't clear to me at the time). And to do that you have to visit AdSense and input your billing address - at least after doing that I received a confirmation email. Hope it shines more light on the problem many people have, since this detail is almost never mentioned and I feel someone might be looking for the solution in the wrong place (as I did).

Thanks for the tips ;)
