### ISSUE TITLE
A Way to Load Rewarded Video Immediately

### ISSUE THREAD

**Issue by KanataEXE** [Shin-NiL/Godot-Android-Admob-Plugin#134]
**Godot version: 3.2.3**

**AdMob Plugin version: 4.1.1**

**Issue description:**
When my android game started, the players have to wait for a few seconds (2-3 seconds) before they can get coins through watching ads.

Is there a way to immediately load the rewarded video?

**Comment by haruntrkmn** [comment]
I don't think so, since it requires time for server to answer your ad request.

**Comment by Merlin1846** [comment]
Just call 
	$AdMob.load_interstitial()
To load the ad. And this,
	$AdMob.show_interstitial()
to show the ad.
