### ISSUE TITLE
Showing test ads instead of real ads

### ISSUE THREAD

**Issue by hayderkharrufa** [Shin-NiL/Godot-Android-Admob-Plugin#142]
Godot v3.2.3
Godot-Android-Admob-Plugin v4.1.1

Admob plugin showing test ads instead of real ads after publishing to production on Play Store.

I already:
- Added my App ID to AndroidManifest.xml
- Set my Ad Unit ID to my own rewarded_id from Admob.
- Set is_real to true.
- Uncheck Export with Debug when exporting.

**Comment by hayderkharrufa** [comment]
Apparently, the problem I had was due to using test ads on an admob node outside the scene. Works fine now after I set all the nodes to real ads.

**Comment by jingMV** [comment]
how do you fixed it?

**Comment by rifat-hossain** [comment]
I did not notice it either. You just need to check the "IsReal" box of the AdMob node and your in-game ads will show real ads.
![image](https://user-images.githubusercontent.com/35867913/126889437-9fa98940-66e8-4e2a-bbf1-8e6909c10acc.png)

That's it.
> how do you fixed it?

**Comment by jingMV** [comment]
> 
> 
> > how do you fixed it?
> 
> I did not notice it either. You just need to check the "IsReal" box of the AdMob node and your in-game ads will show real ads.
> ![image](https://user-images.githubusercontent.com/35867913/126889437-9fa98940-66e8-4e2a-bbf1-8e6909c10acc.png)
> 
> That's it.

i did it too, but same result
