### ISSUE TITLE
Update for 3.3 Stable

### ISSUE THREAD

**Issue by SkanerSoft** [Shin-NiL/Godot-Android-Admob-Plugin#146]
**Godot version:**
3.3 stable

**AdMob Plugin version:**
4.1.1

**Issue description:**
Crash on startup on my device.
I cannot connect the phone to the computer for log with ADB

**Comment by Lozamded** [comment]
I have the same problem.

**Comment by tungkradle** [comment]
Same problem confirmed.

**Comment by Langrisser001** [comment]
Same problem, crash on startup.

I try running the demo, but the problem persist. I already follow the steps in Setup.

I don't know if this correlate with crash, but I found this in logcat

```
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException:

******************************************************************************
* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
* should follow the instructions here:                                       *
* https://googlemobileadssdk.page.link/admob-android-update-manifest         *
* to add a valid App ID inside the AndroidManifest.                          *
* Google Ad Manager publishers should follow instructions here:              *
* https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
******************************************************************************
```

**Comment by choyg** [comment]
It's a simple fix. Check my [fork's diff](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/compare/main...choyg:main). I also published a [release](https://github.com/choyg/Godot-Android-Admob-Plugin/releases/tag/v5.0.0) for your convenience. You can grab the other `admob-lib` files from this repo.

**Comment by choyg** [comment]
Fwiw the underlying admob library is [evolving](https://developers.google.com/admob/android/migration) as well so there's likely going to be additional breaking changes needed if people want to use the latest and greatest on both Godot and Admob.

**Comment by raeddarweesh** [comment]
Thank you @choyg. Your fork is working perfect.
