### ISSUE TITLE
Is It Okay to Copy-Paste the Script?

### ISSUE THREAD

**Issue by KanataEXE** [Shin-NiL/Godot-Android-Admob-Plugin#152]
**Godot version: 3.3**

**AdMob Plugin version: 5.0.0**

**Issue description:**
Is it okay to copy-paste the script into the game? There will be no problem doing it, right?

**Comment by Merlin1846** [comment]
Why bother copy and pasting? The script won't even work without the rest of the plugin, just download the plugin and follow the instructions.
