### ISSUE TITLE
Rewarded interstitial

### ISSUE THREAD

**Issue by marufaytekin** [Shin-NiL/Godot-Android-Admob-Plugin#155]
**Godot version:**
3.2.3 stable

**AdMob Plugin version:**

**Issue description:**

I use this plugin for Rewarded and interstitial as separately fine but when I try to fetch "Rewarded interstitial" ad with showInterstitial() I get an error 0. 

Does this plugin support Rewarded interstitial ads? or how can I display Rewarded interstitial ads?

Regards,
Maruf

**Comment by Shin-NiL** [comment]
Rewarded interstitial is not supported, sorry.
