### ISSUE TITLE
Ad keeps reappearing

### ISSUE THREAD

**Issue by cgeadas** [Shin-NiL/Godot-Android-Admob-Plugin#16]
**Godot version:**
3.2

**Issue description:**
I'm trying only with the Admob Test Interstitial unit (ca-app-pub-3940256099942544/1033173712), and with:
```
func _on_Admob_interstitial_loaded():
	admob.show_interstitial()
	pass
```
I get the ad respawning. Everytime I close it, it reappears after some seconds. Do I need to call some function to stop it?

**Comment by anisc** [comment]
I think that every time you close it, it load another interstitial, and when it is loaded, it will show. 
You should load the interstitial on the ready and show it  when the player die.

**Comment by cgeadas** [comment]
Yes. You're right.
Out of the callback, admob.show_interstitial() works well.
