### ISSUE TITLE
Showcase additions and video tutorial

### ISSUE THREAD

**Issue by an0mali** [Shin-NiL/Godot-Android-Admob-Plugin#160]
https://play.google.com/store/apps/details?id=org.dtgames.dodecoingame

https://play.google.com/store/apps/details?id=com.dtgames.flappyunicorn

https://play.google.com/store/apps/details?id=org.dtgames.trihard

I also created a video tutorial on how to implement this if you want to link it-
https://youtu.be/0a6EvlNgLL0

**Comment by Shin-NiL** [comment]
Thank you very much bro. I've added your video on the readme file.
