### ISSUE TITLE
Toggle isReal automatically when build production

### ISSUE THREAD

**Issue by kyoz** [Shin-NiL/Godot-Android-Admob-Plugin#164]
**Godot version: 3.3**

**AdMob Plugin version: 5.0**

**Issue description:**
Can i toggle this by gdscript on runtime. Cause if i have toggle this in inspector, sometime in the future, when maintaining my project, i may forget it and cause new release is full of test ads. :(

**Comment by Merlin1846** [comment]
Just run
`if not OS.is_debug_build():
      $AdMob.is_real = true`

This will tell it to show real ads if it is NOT running in the editor OR a debug build. Their you go it's automated.

**Comment by kyoz** [comment]
Or i forgot this, i have actually solve before. Btw thank you very much.😊

**Comment by Merlin1846** [comment]
Sorry that code might not work use this instead.

if OS.is_debug_build():
	$AdMob.is_real_set(false)
else:
	$AdMob.is_real_set(true)
