### ISSUE TITLE
Request to update admob dependencies 

### ISSUE THREAD

**Issue by MrZak-dev** [Shin-NiL/Godot-Android-Admob-Plugin#168]
**Godot version:**
3.4
**AdMob Plugin version:**
latest
**Issue description:**

Request to update the plugin to use the latest google ads sdk `gms:play-services-ads:20.2.0`

**Comment by Funmungus** [comment]
20.0.0 is the highest I have gotten to work with Godot 3.4.4.  The gms Ads SDK above 20.0.0 requires a target SDK 31 or 32, and Godot compiles with target SDK 30.

**Comment by Funmungus** [comment]
Edit: GMS Ads SDK above 21.0.0 requires target SDK 31 or 32, so I am using that version.  This will be updated in my changes.

**Comment by Shin-NiL** [comment]
Updated to gms:play-services-ads:20.4.0
