### ISSUE TITLE
has problem with plugin develop

### ISSUE THREAD

**Issue by 2439905184** [Shin-NiL/Godot-Android-Admob-Plugin#170]
**Godot version:*3.3.3*

**Issue description:**

I am a Chinese godot user, admob is may not be a good thing in China ,because the great firewall.
So I want to develop an ad plugin in godot 3.3.3. This is called YomobPlugin.
But log cat show this :Nonexistent function 'test' in base 'Nil'. when click button.
But I got the Plugin.
![image](https://user-images.githubusercontent.com/29478722/131245556-b77a3691-7f77-4d72-9f73-12e9aadcab70.png)
![image](https://user-images.githubusercontent.com/29478722/131245564-cca2d508-2092-4b88-baab-6b6d5d35021e.png)
this method returned true.
So godot 3.3.3 use new api to write plugin with  @UsedByGodot instead of getPluginMethods()
But I dont't know why it says this plugin object is Nil ."Nonexistent function 'test' in base 'Nil"
![image](https://user-images.githubusercontent.com/29478722/131245622-b826a5ae-5f6f-4d70-8e1c-37a5d6f5fe79.png)
I used this simple function . But can't return the string .I learn code from your plugin code

**Comment by Funmungus** [comment]
There are a few more steps involved.  Here is the full documentation on creating a plugin: https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html

1. Create an Android library: https://developer.android.com/studio/projects/android-library
2. Add the Godot library dependency (godot-lib.3.3.3.stable.release.aar)
3. Create a class extends org.godotengine.godot.plugin.GodotPlugin and implement the code in your snippet.
4. Update the plugin AndroidManifest.xml file: <meta-data> tag for your plugin name and Java/Kotlin class.
5. Build plugin library, the artifact is an .aar file, probably YomobPlugin-release.gdap.
6. Create a Godot Android Plugin configuration file, YomobPlugin.gdap.
7. In Godot, in the Android export dialog, in the Plugins section, enable YomobPlugin.

**Comment by 2439905184** [comment]
Thank you. I have finished the plugin now(test ad).
In the past, I dont't know some details under what gradle does.
