### ISSUE TITLE
Dirtfall - Vacuum Cleaning Sim

### ISSUE THREAD

**Issue by goldspark** [Shin-NiL/Godot-Android-Admob-Plugin#179]
**Godot version:**
3.3.3 Mono
**AdMob Plugin version:**
5.1.0
**Issue description:**
Admob is working perfectly even tho its a Mono version here is a game link: [https://play.google.com/store/apps/details?id=com.goldspark.cleaner.dirtfall](url)

AdMob working can be seen in Shop on button "WATCH AD FOR $"

**Comment by Shin-NiL** [comment]
Thank you very much!
