### ISSUE TITLE
Loading a banner displays it automatically.

### ISSUE THREAD

**Issue by Torguen** [Shin-NiL/Godot-Android-Admob-Plugin#185]
**Godot version:**
3.4.1 rc1 mono
**AdMob Plugin version:**
5.1.0
**Issue description:**
Loading a banner displays it automatically.
Even if the user never did "show_banner".

To fix this call "hide_banner" immediately after "load_banner".

The expected is to use "load_banner" and not show the ad until the user calls "show_banner".

**Comment by vetu11** [comment]
I think this is the intended behavior.

**Comment by Shin-NiL** [comment]
I can confirm this is the expected behavior.

**Comment by Torguen** [comment]
Ah well I would expect what I mentioned in the report.
I didn't do show_banner so why does the banner show automatically?

It would make sense to put "show_banner" in the broadcast of the "banner_loaded" signal, that makes sense to me.

**Comment by Shin-NiL** [comment]
This is a "legacy" behavior from an old lib. I agree it could be changed in the future.
