### ISSUE TITLE
I have a problem with  Shin-NiL / Godot-Android-Admob-Plugin 

### ISSUE THREAD

**Issue by robin10-20** [Shin-NiL/Godot-Android-Admob-Plugin#189]
**Godot version:*3.4*

**AdMob Plugin version:*5.1.0*

**Issue description:**

**Comment by Funmungus** [comment]
The current release is built with Godot 3.3.3. I am currently working on changes to build with 3.4.4. If you need another version of Godot you may have to build this plugin with the versions you need.
