### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by gingy-c** [Shin-NiL/Godot-Android-Admob-Plugin#194]
**Godot version:**
3.4.4
**AdMob Plugin version:**
5.1.0
**Issue description:**
Found a typo in 'ammount'
![image](https://user-images.githubusercontent.com/47944606/180610921-047e53d1-0e86-4f4a-9a8d-8a4a369a7b43.png)

**Comment by Shin-NiL** [comment]
Fixed.
