### ISSUE TITLE
Support for Rewarded Interstitial Ads

### ISSUE THREAD

**Issue by cengiz-er** [Shin-NiL/Godot-Android-Admob-Plugin#197]
[Rewarded interstitial](https://support.google.com/admob/answer/9884467) is a type of incentivized ad format that allows you offer rewards for ads that appear automatically during natural app transitions. Unlike rewarded ads, users aren't required to opt-in to view a rewarded interstitial.

More at: https://developers.google.com/admob/android/rewarded-interstitial

This plugin is currently lacking support for this new type of ad from Google AdMob.

**Comment by Shin-NiL** [comment]
Rewarded interstitial added in v6.1.0
