### ISSUE TITLE
loadbanner() is causing crash

### ISSUE THREAD

**Issue by gamergamesz** [Shin-NiL/Godot-Android-Admob-Plugin#2]
3.2 alpha

removing loadbanner() from ready function works but using it crashes the apk as soon as it starts.
might be something to do with layout method

**Comment by Shin-NiL** [comment]
Yeah, I'll try to find a way to access the layout property, if not, I'll have to ask the godot devs to give us a way to do it.

**Comment by Shin-NiL** [comment]
I've opened an issue: https://github.com/godotengine/godot/issues/32827
