### ISSUE TITLE
Demo Application not working

### ISSUE THREAD

**Issue by BilawalSarwar** [Shin-NiL/Godot-Android-Admob-Plugin#20]
**Godot version:**
3.2

**Issue description:**

I downloaded and run the demo. I only install custom android template. Its is not working on android phone. It crashes as soon as starts. I tried the same code in another application. Only banner is working. When i tried to run other 2, again it crashed. You have any idea, what can be the issue. Thanks

**Comment by Shin-NiL** [comment]
Tested and it worked fine. Please take a look at the troubleshooting section on the readme file.

**Comment by BilawalSarwar** [comment]
Below is the error i am getting. but there is no reason why its not loaded.

W/Ads: Not retrying to fetch app settings
W/w: AdMob: showInterstitial - interstitial not loaded
I/Choreographer: Skipped 52 frames!  The application may be doing too much work on its main thread.
I/zygote: Background concurrent copying GC freed 31116(1483KB) AllocSpace objects, 14(556KB) LOS objects, 49% free, 3MB/6MB, paused 107us total 1.449s
I/Ads: Scheduling ad refresh 70000 milliseconds from now.
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21001
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 21001

**Comment by Shin-NiL** [comment]
Seems like you're calling show_interstitial before load_interstitial

**Comment by BilawalSarwar** [comment]
This is my method:

func _ready():
	admob.load_interstitial()
	admob.show_interstitial()
# warning-ignore:return_value_discarded
	get_tree().connect("screen_resized", self, "_on_resize")

**Comment by BilawalSarwar** [comment]
I did everything same. If its issue in script then why only banner is working but not others.

**Comment by Shin-NiL** [comment]
Are you using the ads IDs from the demo? Are you showing real or test ads?

**Comment by BilawalSarwar** [comment]
I am using test ads

**Comment by BilawalSarwar** [comment]
Everything is exact same as in Demo. Even when i run demo it crashes immediately as soon as starts. I can send the apk generated from Demo

**Comment by BilawalSarwar** [comment]
I just added Android Build Template and run it

**Comment by BilawalSarwar** [comment]
I am not sure if OS has anything to do with this as i am running Godot 3.2 Stable on **macOS** not on windows

**Comment by Shin-NiL** [comment]
>I am not sure if OS has anything to do with this as i am running Godot 3.2 Stable on macOS not on windows

I don't this so. 
Unfortunately I'm unable to replicate the issue, as I said before the demo project works fine to me.

**Comment by BilawalSarwar** [comment]
It's working now.
