### ISSUE TITLE
Real ads not loading on Android 9 but loading on Android 6

### ISSUE THREAD

**Issue by cgeadas** [Shin-NiL/Godot-Android-Admob-Plugin#22]
**Godot version:**
3.2

**Issue description:**
With exactly the same project, run with debug from Godot IDE connected to an Android 9 phone, I get test ads working but error 3 with real ones. If I disconnect from the Android 9 phone and connect to the Android 6.0.1 phone and run my project again I get both real and test ads working.
Although error 3 is usually a problem with the admob network, in this case I don't think it is, since the only difference between working and not working is the equipment/Android version.

**Comment by anisc** [comment]
On my Android 9 both real and test ads (banner) function with no problems.
My game is 2 scenes: title scene and game scene.

on ready:(game scene)
admob.load_banner()
admob.show_banner()

**Comment by Shin-NiL** [comment]
As @anisc and other users reported, it seem to be working with Android 9. Maybe there's another thing different between you 2 deployments.
