### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by quanghuy6698** [Shin-NiL/Godot-Android-Admob-Plugin#225]
**Godot version: 3.5.2**
**AdMob Plugin version: 6.2.0**
**Issue description:**
I am unable to make plugin work
I tested with both test ads and real ads, but nothing work
I tested with both emulator and real device, also nothing work, it doesnt show any ads

**My script:**
```
extends Node
onready var ad_mob = $AdMob
func _ready():
   ad_mob.load_banner()
func show_banner_ads():
   ad_mob.show_banner()
```

**Here is adb logcat:** (I copy error only)
```
08-13 00:34:18.001   193   196 E android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup34: Permission denied
08-13 00:34:18.027   193   196 E android.system.suspend@1.0-service: Error opening kernel wakelock stats for: wakeup35: Permission denied
08-13 00:34:21.489   446   446 E netmgr  : qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:network' service: Invalid argument
08-13 00:34:21.503   446   446 E netmgr  : Failed to open QEMU pipe 'qemud:network': Invalid argument
08-13 00:34:23.760   454   454 E wifi_forwarder: qemu_pipe_open_ns:62: Could not connect to the 'pipe:qemud:wififorward' service: Invalid argument
08-13 00:34:23.760   454   454 E wifi_forwarder: RemoteConnection failed to initialize: RemoteConnection failed to open pipe
```
Please help me out.

**Comment by vipulbehl** [comment]
The plugin does work with the latest release with godot 3.5.2. 

Can you check if the versions are compatible, also start logcat with ```adb logcat *:W``` this will give you warning logs as well. I suspect the real error isn't there in the stacktrace that you shared above.

**Comment by kychan92** [comment]
It looks like it's complaining about a permission issue (Permission denied).
Make sure you follow all the steps in the manual, specifically:
on the Project -> Export... -> Android -> Options ->
Permissions: check the permissions for **Access Network State** and **Internet**
Custom Template: check the Use Custom Build
Plugins: check the Godot Ad Mob (this plugin)
