### ISSUE TITLE
ERROR he heap size specified, -Xmx4536m, exceeds the maximum representable size

### ISSUE THREAD

**Issue by eliecer696** [Shin-NiL/Godot-Android-Admob-Plugin#226]
when i tray to play test my app on my device i get this error am using godot 3.5.2 is there a way to fix this
FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the User Manual chapter on the daemon at https://docs.gradle.org/7.4/userguide/gradle_daemon.html
Process command line: C:\Program Files (x86)\Eclipse Adoptium\jdk-11.0.20.101-hotspot\bin\java.exe --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx4536m -Dfile.encoding=windows-1252 -Duser.country=US -Duser.language=en -Duser.variant -cp C:\Users\elio\.gradle\wrapper\dists\gradle-7.4-bin\c0gwcg53nkjbqw7r0h0umtfvt\gradle-7.4\lib\gradle-launcher-7.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4
Please read the following process output to find out more:
-----------------------
Invalid maximum heap size: -Xmx4536m
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by lele25811** [comment]
I solved this error: Uninstall your current JDK, and install JDK 18, set JAVA_HOME to your JDK 18 folder

**Comment by eliecer696** [comment]
many thanks for the fixe i appreciated

**Comment by eliecer696** [comment]
> I solved this error: Uninstall your current JDK, and install JDK 18, set JAVA_HOME to your JDK 18 folder

how do i set JAVA_HOME  to my jdk folder

**Comment by lele25811** [comment]
-> Search for "Environment Variables" then select "Edit the system environment variables" 
-> Click the Environment Variables button 
-> Under System Variables, click New or if you have yet the name JAVA_HOME you can modity it.

**Comment by eliecer696** [comment]
> -> Search for "Environment Variables" then select "Edit the system environment variables" -> Click the Environment Variables button -> Under System Variables, click New or if you have yet the name JAVA_HOME you can modity it.

thank a lot manny manged to get it working i also had to tweak the build.gradel and it worked like a charm

**Comment by lele25811** [comment]
> > -> Search for "Environment Variables" then select "Edit the system environment variables" -> Click the Environment Variables button -> Under System Variables, click New or if you have yet the name JAVA_HOME you can modity it.
> 
> thank a lot manny manged to get it working i also had to tweak the build.gradel and it worked like a charm

If you have solved the problem, I recommend closing the issue :)
