### ISSUE TITLE
No GodotAdmob.gdap and GodotAdmob.release.aar in admob-plugin directory

### ISSUE THREAD

**Issue by daundev** [Shin-NiL/Godot-Android-Admob-Plugin#238]
**Godot version: 3.5.3**

**AdMob Plugin version: 6.2.0**

**Issue description:**

> extract the content of the admob-plugin directory (GodotAdmob.gdap and GodotAdmob.release.aar from the zip package) inside the res://android/plugins directory on your Godot project.

sorry there is no GodotAdmob.gdap and GodotAdmob.release.aar in admob-plugin directory, where is it?

**Comment by l2toplist** [comment]
https://github.com/Shin-NiL/Godot-Android-AdMob-Plugin/releases

**Comment by daundev** [comment]
okay previously I downloaded the source code
