### ISSUE TITLE
Startup Crash with Android -> Modules string added

### ISSUE THREAD

**Issue by kristiannotari** [Shin-NiL/Godot-Android-Admob-Plugin#25]
**Godot version:**
3.2

**Issue description:**
I've successfully tried working with your plugin. I have setup two different Godot projects which uses this plugin and they work correctly. Tested with test ads on real android devices.

Now, after some days, even if I changed nothing, testing on real android device, it seems to crash the entire app, in both projects. The error is that the app crash on launch, after installation. (I know it seems untrue but...).
I know is something related to this plugin (maybe) because if I remove the `org/godotengine/godot/GodotAdMob` string in the Project Settings -> Android -> Modules, it then works fine.

Any ideas?

**Comment by Shin-NiL** [comment]
Could you check the output log with logcat?
`adb logcat -s godot`

**Comment by kristiannotari** [comment]
Sorry for me not being able to answer earlier. We have fixed the error playing with the manifest and build files inside the android export template. Seems like something related to the configuration of the plugin. I can't say more cause it has not been done by me. As soon as I can, I'll reach you.

If you can, please confirm or not my guesses, trying the plugin on a fresh new Godot project, Godot version 3.2.1.

(also, the "use custom build" flag inside the android export preset should be set to false if the plugin is the only "custom thing" we have, since it uses the new android plugin system by Godot, right?)

**Comment by Shin-NiL** [comment]
>(also, the "use custom build" flag inside the android export preset should be set to false if the plugin is the only "custom thing" we have, since it uses the new android plugin system by Godot, right?)

If you're using this plugin it should be set to true.

**Comment by kristiannotari** [comment]
I've never set it to true and it worked well for the first days :)
Don't know how, but it did. I did not flag the custom build because I thought it would not be needed since it's not a proper custom export template but it uses android plugin system.

I've now read the docs more carefully and did noticed the "custom build" flag set to true while using the new android plugin system. My bad for that. Maybe it's just things messed up by my side.

If I can reach the ones who made it work here, I'll answer you with all the details.

**Comment by Thibb1** [comment]
**Got the same issue**
OS target (Android/iOS):Android

Godot version:3.2.1

Issue description:
App crashes on launch (adb installation). Works fine inside Godot. Logcat shows this error :
`FATAL EXCEPTION: main`
`java.lang.NullPointerException: Attempt to invoke virtual method 'int `com.google.android.gms.ads.AdView.getVisibility()' on a null object reference`

I will try to install via export menu

**Comment by Shin-NiL** [comment]
@Thibb1 which admob plugin version are you using?

**Comment by Thibb1** [comment]
I tried 3 versions and this one too.
I managed to fix it
The error is due because I used `admob.show()` or `admob.hide()` before `admob.load()`

**Comment by Shin-NiL** [comment]
>The error is due because I used admob.show() or admob.hide() before admob.load()

This issue should be already fixed in the newest version (2.2.0).

**Comment by Shin-NiL** [comment]
Was this issue solved?

**Comment by MintStudios** [comment]
@Shin-NiL this issue seems to be resolved

**Comment by Shin-NiL** [comment]
Thanks @MintStudios, I'm closing it now. We can reopen anytime if needed.
