### ISSUE TITLE
Will there be an update for 3.2.2 ?

### ISSUE THREAD

**Issue by gamergamesz** [Shin-NiL/Godot-Android-Admob-Plugin#26]

**Comment by Shin-NiL** [comment]
Is it not working with beta?

**Comment by cgeadas** [comment]
I think @gamergamesz is asking about the new plugin architecture, starting with 3.2.2 https://github.com/godotengine/godot/pull/36336

Although both systems will accepted during 3.2.x releases, updating for the new and "standard" plugin architecture would be good.

**Comment by Shin-NiL** [comment]
I've tried, but without success. It's easier for the final user but a little more laborious for the developer :(

**Comment by cgeadas** [comment]
@Shin-NiL I believe you.
But the announcement(https://godotengine.org/article/dev-snapshot-godot-3-2-2-beta-2) states that "Fredia has already started helping some plugin authors to update theirs to the new v1 system, feel free to ask if you need help too." so, since help is available, maybe you can take some advantage of it. We would surely appreciate that you continue to provide your plugin :-)

**Comment by Shin-NiL** [comment]
Thanks @cgeadas, I'll try again for sure.

**Comment by Shin-NiL** [comment]
@gamergamesz  @cgeadas
We have some progress [here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/tree/plugin-v1).

**Comment by ricardo-fuertes** [comment]
Does it work with godot 3.2.2?
I am using Debian 10 and try with Godot 3.2.2 64bit, rc1, beta 1, beta 2, beta 3 and beta 4, but they all showed the same error

06-14 23:57:20.989  9511  9568 I godot   : Godot Engine v3.2.2.rc1.official - https://godotengine.org
06-14 23:57:21.000  9511  9568 I godot   : OpenGL ES 2.0 Renderer: Mali-G71
06-14 23:57:21.044  9511  9568 I godot   : OpenGL ES 2.0 Batching: ON
06-14 23:57:21.053  9511  9568 I godot   :  
06-14 23:57:21.289  9511  9568 I godot   : Admob Java Singleton not found

I think my problem is in on the Project -> Export... -> Android -> Options -> Plugins: check the Godot Ad Mob (this plugin), this option not found in Godot only have Godot Payment

**Comment by Shin-NiL** [comment]
>I think my problem is in on the Project -> Export... -> Android -> Options -> Plugins: check the Godot Ad Mob (this plugin), this option not found in Godot only have Godot Payment

Yeah, that's the case. To this option be available you need the the .aar and .gdap files. I'll put them on the release tabs when the stable version were released. Meanwhile, you can try [these](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/4779905/GodotAdMobPlugin.zip) (3.2.2 RC1).

Extract the content inside the ```res://android/plugins``` directory and try again.

**Comment by MaaaxiKing** [comment]
Will you make it possible that ads can be seen on the PC too someday? Would be really helpful, you wouldn't have to connect the PC to the phone everytime just for testing if the ads work.

**Comment by MaaaxiKing** [comment]
Do you think the new plugin version will be released around that time the new Godot version will be released or do you need much more time? I have to plan my release xD

**Comment by MaaaxiKing** [comment]
Will IOS get a new plugin version too?

**Comment by Shin-NiL** [comment]
@MaaaxiKing 
>Will you make it possible that ads can be seen on the PC too someday? Would be really helpful, you wouldn't have to connect the PC to the phone everytime just for testing if the ads work.

It's how the AdMob works, only Android & iOS are supported by them and this plugin just works with Android.

>Do you think the new plugin version will be released around that time the new Godot version will be released or do you need much more time? I have to plan my release xD

If there's no dramatic changes until there, it's done. It's already working fine with Godot 3.2.2 RC1 :)


>Will IOS get a new plugin version too?

Right now the only way to use AdMob with Godot is recompiling the engine with a module addon. Even if Godot add similar plugin support one day, I can't do it, as I don't have and don't develop for iOS.

**Comment by ricardo-fuertes** [comment]
> > Creo que mi problema está en el Proyecto -> Exportar ... -> Android -> Opciones -> Complementos: marque Godb Ad Mob (este complemento), esta opción no se encuentra en Godot solo tiene Godot Payment
> 
> Si, ese es el caso. Para que esta opción esté disponible, necesita los archivos .aar y .gdap. Los pondré en las pestañas de lanzamiento cuando se lanzó la versión estable. Mientras tanto, puede probar [estos](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/4779905/GodotAdMobPlugin.zip) (3.2.2 RC1).
> 
> Extraiga el contenido dentro del `res://android/plugins`directorio e intente nuevamente.

Thank you very much. It works for me.

**Comment by ricardo-fuertes** [comment]
> > I think my problem is in on the Project -> Export... -> Android -> Options -> Plugins: check the Godot Ad Mob (this plugin), this option not found in Godot only have Godot Payment
> 
> Yeah, that's the case. To this option be available you need the the .aar and .gdap files. I'll put them on the release tabs when the stable version were released. Meanwhile, you can try [these](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/4779905/GodotAdMobPlugin.zip) (3.2.2 RC1).
> 
> Extract the content inside the `res://android/plugins` directory and try again.

Thank you very much. It works for me.

**Comment by MaaaxiKing** [comment]
Please add `export var enabled := true`, so you can easily enable and disable ads. Of course, you'll have to write in every function `if enabled == true`. That shouldn't be too diffictul ;D

**Comment by Shin-NiL** [comment]
@ricardo-fuertes Nice! Thanks for testing ;)

@MaaaxiKing Good idea, could you please open a new issue with this request? This way I'll not forget to try to add this functionality in the future.

**Comment by MaaaxiKing** [comment]
Done :D

**Comment by Shin-NiL** [comment]
GodotAdMob Plugin 4.0.0 was released using the newest plugin system.
