### ISSUE TITLE
ads not showing on android devices

### ISSUE THREAD

**Issue by DALHOUM-Ahmed** [Shin-NiL/Godot-Android-Admob-Plugin#28]
Hi, i use Godot 3.2.1 my problem is that ads are not showing after installing my exported apk to my android device ( connected to a wifi so surely it has internet connection )
the logcat shows that everything works as expected the only strange message i get is when loading ads it shows this message:
**AdMob: onAdFailedToLoad(int errorCode) - error code: 3**

can anyone help me with this i am really struggling in here 
sorry for my poor english, i am not a native english speaker

**Comment by DALHOUM-Ahmed** [comment]
btw i am using my own ids from the google admob and even when using test ids it doesn't work

**Comment by MintStudios** [comment]
Are you using test ads?

If you are using real ads, it takes a day or 2 for real ads to work. This happened to me recently, 2 days ago, and now it's working. Error code 3 means that there are no ads to go in those spots. Don't worry, wait, and they will work.

**Comment by DALHOUM-Ahmed** [comment]
thank you, real ads are working for me now after waiting about 24 hours like you said .but the only issue that i have now is that ads loading only works when the **is_real** variable is set to false, i don't understand why i only want to know if this will affect the monetization process

**Comment by Shin-NiL** [comment]
Maybe it'll take more time to you get real ads. The is_real should be set to true on the release apk, otherwise you'll not get your monetization.

**Comment by Shin-NiL** [comment]
@DALHOUM-Ahmed was this issue solved?

**Comment by MintStudios** [comment]
@Shin-NiL this issue seems to be resolved
