### ISSUE TITLE
SDK version

### ISSUE THREAD

**Issue by MintStudios** [Shin-NiL/Godot-Android-Admob-Plugin#29]
**Godot version:**
3.2.1

Just a question. What is the version of the google Admob SDK is the one in this plugin?

**Comment by DALHOUM-Ahmed** [comment]
i followed this tutorial it uses this plugin to integrate admob i hope this helps
[admob android integration](https://godotlearn.com/godot-3-2-how-to-integrate-google-ads-admob-for-android/)

**Comment by Shin-NiL** [comment]
It's using play-services-ads:16.0.0 right now.

**Comment by MintStudios** [comment]
@Shin-NiL you should really update it. Without the newer 18.10 version, we won't be getting user metrics, which sucks greatly.

**Comment by MintStudios** [comment]
The newest version is 19.1.0, you should really upgrade it.

**Comment by MintStudios** [comment]
#30

**Comment by Shin-NiL** [comment]
I was waiting to use the newest Godot Android plugin system (v1) to upgrade it together. But as I failed with this task I'll reconsider to just upgrade the Admob SDK.

**Comment by MintStudios** [comment]
@Shin-NiL We could use the pull request I made to make changes to the code.

**Comment by Shin-NiL** [comment]
Thanks @MintStudios, I've just did a commit with the changes. Need some testing though.

**Comment by Shin-NiL** [comment]
If everything goes fine, I'll create a new release.

**Comment by Shin-NiL** [comment]
Please check https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/releases/tag/v3.0-beta

**Comment by MintStudios** [comment]
So does it work?

**Comment by Shin-NiL** [comment]
I have tested just with my demo project using test ads and was working.
