### ISSUE TITLE
Export demo project error

### ISSUE THREAD

**Issue by SmartySmart702** [Shin-NiL/Godot-Android-Admob-Plugin#3]
Godot 3.2 Alpha 2

I'm getting this error when I try to export the admob demo project to android.
Maybe I did something wrong? I copied the "admob-plugin" folder into the "android" folder in the project folder. 
Without the admob-plugin folder, there was no error while exporting the project.

![error text](https://user-images.githubusercontent.com/42713365/67307264-86ac0d00-f4f8-11e9-9bd4-8008f0902fe3.jpg)

**Comment by Shin-NiL** [comment]
There was [some issues](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/3) with 3.2 alpha 2, they are already fixed on Godot master. You have two options for now: compile the Godot master branch by yourself or wait for a new beta build.

**Comment by SmartySmart702** [comment]
Thanks! Works perfect now.

**Comment by Shin-NiL** [comment]
Thanks for testing ;)

**Comment by SmartySmart702** [comment]
What is the reason for using this addon for Godot 3.2 or higher? Are addons from Godot 3.1 not compatible with Godot 3.2?

**Comment by Shin-NiL** [comment]
This Android _plugin_ is using a [new system](https://godotengine.org/article/godot-3-2-will-get-new-android-plugin-system) available only on Godot 3.2. Before that, for using this kind of 'addon' you should use another method, called _module_ (this repository is a port of a [module](https://github.com/kloder-games/godot-admob)). The drawback of the modules is that for use it you need to recompile the whole Godot engine. 

You can still use the modules after 3.2, but the plugins are much easier.

**Comment by SmartySmart702** [comment]
Ah okay. Thanks for the fast answer!

**Comment by SmartySmart702** [comment]
Dont know how I could contact you :D  
Do you know this module? 
https://github.com/FrogSquare/GodotGoogleService

Looks like the developer is inactive since a while (did not response to an e-mail too) but it would be really nice to have this for the new plugin system.
So maybe you would like to fork it and make it compatible with the new plugin system (dont know how hard it is to "upgrade" to the new plugin system so maybe it is to much effort but I just wanted to suggest it :D)

**Comment by Shin-NiL** [comment]
Yes, I know it. But I have no plans to deal with another module for while ;(
