### ISSUE TITLE
farklı rewarded reklam göstermek

### ISSUE THREAD

**Issue by mthnzbk** [Shin-NiL/Godot-Android-Admob-Plugin#31]
**Godot version:**
3.2.1

**Admob Plugin version:**
2.2.0
**Issue description:**
I want to show 2 rewarded videos that I have defined in the same scene for different situations. Can we enter more than one id in rewarded id?
show_rewarded(id1) load_rewarded(id1) - show_rewarded(id2) load_rewarded(id2)

**Comment by Shin-NiL** [comment]
No you can't. The Godot Plugin and even the AdMob SDK for rewarded video are both singletons, so you can only create one instance for each type of ad.
