### ISSUE TITLE
Real ads switch to test ads

### ISSUE THREAD

**Issue by rosspetukhov** [Shin-NiL/Godot-Android-Admob-Plugin#32]
**Godot version:3.2.1**

**Admob Plugin version:**

**Issue description: Hi! I've published the app, but many users say they see test ads. But I can see imrpessions are generated on my admob account. I've put a print function before load_banner and noticed that first my banner details are priting, but then they switch to test banner IDs. Do you know why? Thank you! . **

**Comment by Shin-NiL** [comment]
Which version of this plugin are you using?

**Comment by rosspetukhov** [comment]
Hi, thanks for a quick reply! I believe it is 3.0.0 (can't see the version in plugin myself, maybe im blind). Ive downloaded it on 5 March 2020, and gradle has "api ('com.google.android.gms:play-services-ads:19.1.0')", so I assume it is 3.0.0. Thank you!

**Comment by rosspetukhov** [comment]
I've uploaded my files to github, maybe it will make it clearer:
LevelTemplate is the main gd for any level (where I have a banner)
And it has your admob file as a child of the scene
https://github.com/rosspetukhov/admob_issue/tree/master

**Comment by Shin-NiL** [comment]
It's strange because there's no hardcoded test ID in the plugin code, I don't know why it could be called.

Could you debug the```is_real``` variable?

**Comment by rosspetukhov** [comment]
Yes, it is bizzare! The id changes within the code during gameplay.

I've put this code in admob.gd (sorry if it is a wrong debugging approach, I started programming a month ago only, started godot 2 weeks ago):

```
func load_banner() -> void:
	print("is real: ",is_real, "banner_id: ", banner_id)
	if _admob_singleton != null:
		_admob_singleton.loadBanner(banner_id, banner_on_top)
```

And I ran device using my tablet and remote debug (I pressed on android button in the top right corner of Godot window).

Below is the output when I load a scene with a banner (and no ad showing up!):

` is real: Truebanner_id: ca-app-pub-7971246227051167/8766697250`

I restart the level, and I receive a test ad!: and different input! 

`is real: Truebanner_id: ca-app-pub-3940256099942544/6300978111`

The funny thing, that I can see that I've made 0.4 USD on my admob account, and I have 175 downloads. So money are coming in, but my friend MOSTLY see test ads, but sometimes real ads

**Comment by rosspetukhov** [comment]
The thing that I changed from your script - I've hardcoded my banner id. Admob.gd has this:
var banner_id:String = "ca-app-pub-7971246227051167/8766697250"

And in my levels, I check if person consented to personal ads or not (I've made a scene at the start of the app that asks if you are ok with personal ads. It saves 1 is user agrees, and saves 2 is user disagrees. If there is no file, I force a consent scene to load). I just live in UK, so need to comply with GDPR. And I couldnt find a good Godot plugin for consent. 

```
func _ready():
	var ads = File.new()
	if ads.file_exists(ads_file):
		ads.open(ads_file, File.READ)
		ads_type = ads.get_var()
		ads.close()
		if ads_type==1:
			admob.is_personalized=true
		elif ads_type==2:
			admob.is_personalized=false
	else:
		get_tree().change_scene("res://ConsentSettings/Consent1.tscn")
	
	admob.load_banner()
```

**Comment by Shin-NiL** [comment]
Have you used the demo project as a starting point for yours?

> The thing that I changed from your script - I've hardcoded my banner id. Admob.gd has this:
var banner_id:String = "ca-app-pub-7971246227051167/8766697250"

Don't do that. Instead edit the Admob node properties if you added the Admob node visually:
![image](https://user-images.githubusercontent.com/4077589/83294227-5978b900-a1c3-11ea-9a58-f360567674a9.png)

or set its value via code:
```
    admob.banner_id = "ca-app-pub-7971246227051167/8766697250";
```

You should do it for all properties, including ```is_real```, etc.

**Comment by rosspetukhov** [comment]
Ah, yes, I can see the problem now! I've put test banner ads in the node properties for some levels, and then put a code var banner_id:String = "ca-app-pub-7971246227051167/8766697250". When I removed the code, I can see again the banners showing the test ad values in the node properties! Silly me...  This is why some of my levels had test ads, and some had real ads. Thank you very much, I wouldnt fix it without you!

Just to check that I dont screw it up, is it ok to use below code in a parent node to set personalisation variable based on a saved file ads_file?:
```
func _ready():
	var ads = File.new()
	if ads.file_exists(ads_file):
		ads.open(ads_file, File.READ)
		ads_type = ads.get_var()
		ads.close()
		if ads_type==1:
			admob.is_personalized=true
		elif ads_type==2:
			admob.is_personalized=false
	else:
		get_tree().change_scene("res://ConsentSettings/Consent1.tscn")
	
	admob.load_banner()
```

**Comment by Shin-NiL** [comment]
Nice!
Yeah, the code seems fine to me.

When everything works as expected, please close this issue ;)

**Comment by rosspetukhov** [comment]
Thank you!

**Comment by Shin-NiL** [comment]
Just curious, could you share your published game?

**Comment by rosspetukhov** [comment]
https://play.google.com/store/apps/details?id=com.ross.numbergame12345
Let me know if you found anything wrong there (again, im a noob)

I checked out two fo your games too! I liked them! How come you didn't do more?

**Comment by Shin-NiL** [comment]
I'll test it for sure. I love to see what people create using this plugin.

>I checked out two fo your games too! I liked them! How come you didn't do more?

Thanks! They are a little old, but I learned a lot in the process. I have a main job and little time to spend making another games ;(

**Comment by cgeadas** [comment]
@Shin-NiL I don't know enough about github to know if it's possible or not, but why don't you create some kind of log of the games out there using your plugin? I've one using your plugin and the second is almost done :-)

**Comment by Shin-NiL** [comment]
I was thinking exactly in something like that. Maybe just a .md file here linked in the readme should work.

**Comment by cgeadas** [comment]
The simple, the better. But a way for us to show appreciation for your work and, also, to show how/where your plugin is used.

**Comment by Shin-NiL** [comment]
Take a look: https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/master/showcase.md

**Comment by rosspetukhov** [comment]
Nice!

**Comment by Shin-NiL** [comment]
It's done guys, it's linked on the readme, thank you!

**Comment by cgeadas** [comment]
Can you please include mine? (https://play.google.com/store/apps/details?id=com.bananaonfire.helpluigi) Thank you!

**Comment by Shin-NiL** [comment]
@cgeadas sure, done.

**Comment by cgeadas** [comment]
Thank you!
