### ISSUE TITLE
rewarded video loaded problem

### ISSUE THREAD

**Issue by mthnzbk** [Shin-NiL/Godot-Android-Admob-Plugin#33]
**Godot version:**
3.2.1
**Admob Plugin version:**
3.0
**Issue description:**
I define the admob node in my main scene. There is nothing wrong. However, when I switch to another scene (there is also an admob node in that scene), rewarded video is not loaded. The adb output looks like this:
05-31 15:04:06.244 22925 22925 E godot   :    At: platform/android/java_godot_lib_jni.cpp:1383:Java_org_godotengine_godot_GodotLib_calldeferred() - Condition "!obj" is true.

**Comment by Shin-NiL** [comment]
@mthnzbk it was a bug, should be fixed now on 3.0.1.

**Comment by mthnzbk** [comment]
I tested it, but again I get the same error and rewarded ad doesn't load.

**Comment by Shin-NiL** [comment]
Are you getting the same error?

**Comment by mthnzbk** [comment]
Yes. There is an admob node in every scene that has an advertisement.

**Comment by Shin-NiL** [comment]
But are you calling the load_rewarded_video() again in each one, right?

**Comment by mthnzbk** [comment]
yes

**Comment by Shin-NiL** [comment]
It's strange, I can't reproduce this behavior.

**Comment by mthnzbk** [comment]
problem solved. I think the click-deploy failed because it was not working properly because I installed it as an internal test on google play.
