### ISSUE TITLE
banner ad sizes

### ISSUE THREAD

**Issue by mthnzbk** [Shin-NiL/Godot-Android-Admob-Plugin#36]
**Godot version:**
3.2.1
**Admob Plugin version:**
3.0.1
**Issue description:**
[720p](https://ibb.co/dKPh8H7)
[1080p](https://ibb.co/vmRvgry)
[1080p+ (1920x2340)](https://ibb.co/RgxYWHV)

This is the ad view I tested in nox player. My phone is in fhd+ resolution and looks like the photo. I use banner_resize () but it didn't matter.

**Comment by Shin-NiL** [comment]
The ```banner_resize()``` is only useful when the screen size changes (screen rotation for example), if you screen stills with the same dimension nothing will happen.

This plugin uses Smart Banner, please check the [AdMob documention](https://developers.google.com/admob/android/banner/smart) for more details.

**Comment by mthnzbk** [comment]
so how can i do it fine like fhd resolution? Otherwise it will create a workload for me.

**Comment by Shin-NiL** [comment]
I'm sorry, I don't understand your question. What's the expected result here?

**Comment by mthnzbk** [comment]
https://ibb.co/vmRvgry
I want the same banner resolution in other resolutions as in this screenshot. otherwise it closes the buttons.

**Comment by Shin-NiL** [comment]
I see...
This module only supports Smart Banner right now, other banner fixed sizes can be added in the future though.

Right now you need to adapt your screen to work with:


Ad height | Screen height
-- | --
32 dp | ≤ 400 dp
50 dp | > 400 dp and ≤ 720 dp
90 dp | > 720 dp

**Comment by mthnzbk** [comment]
How do I set the dp? I adjusted my game to 1080p resolution. I also support long screens with keep width.

**Comment by Shin-NiL** [comment]
You can't, [dp varies from device to device](https://material.io/design/layout/pixel-density.html#pixel-density-on-android)
`dp = (width in pixels * 160) / screen density`
A quick workaround I can think is to leave more space reserved for the banner.

**Comment by mthnzbk** [comment]
Could you add the fixed banner(Adaptive?) size feature? Otherwise, I will have trouble putting my game in the store. Or I can solve it by not putting banner ads.

**Comment by Shin-NiL** [comment]
Yeah, I'll try to put some fixed banner sizes in the next update.

**Comment by mthnzbk** [comment]
Thanks

**Comment by Shin-NiL** [comment]
I've updated the code to use adaptive banners, but it's only compatible with Godot 3.2.2.

**Comment by mthnzbk** [comment]
The error I got:

I/godot   ( 3402): Loading Android module: org/godotengine/godot/GodotAdMob
E/godot   ( 3402): **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
E/godot   ( 3402):    At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
--------- beginning of crash
3.2.2 - 4.0

**Comment by Shin-NiL** [comment]
Did you redo all the steps described in the readme file? Godot 3.2.2 is using a new plugin system.
Also, on the Project Settings -> Android -> Modules, remove the string:
`org/godotengine/godot/GodotAdMob` as it is not needed anymore.

**Comment by mthnzbk** [comment]
When I delete it, it says admob singleton was not found.
"I/godot   ( 3905): AdMob Java Singleton not found"

I applied it exactly, but I did not understand this item.
on the Project -> Export... -> Android -> Options ->
Plugins: check the Godot Ad Mob (this plugin) ???

**Comment by Shin-NiL** [comment]
If you did everything right, this option should appears on the export screen:
![image](https://user-images.githubusercontent.com/4077589/85926785-2e43c100-b878-11ea-9477-3642abd007c8.png)

**Comment by mthnzbk** [comment]
![Ek Açıklama 2020-06-27 192006](https://user-images.githubusercontent.com/784614/85926927-4e40a800-b8ab-11ea-8724-a0ad262d7b79.png)
![Ek Açıklama 2020-06-27 192138](https://user-images.githubusercontent.com/784614/85926976-b1cad580-b8ab-11ea-85de-bab95b286fa4.png)
![Ek Açıklama 2020-06-27 192230](https://user-images.githubusercontent.com/784614/85926977-b42d2f80-b8ab-11ea-9b44-096885ba8271.png)
Yes. I deleted the android folder and re-created it.

**Comment by Shin-NiL** [comment]
I got, you should extract the GodotAdMob.gdab and GodotAdMob.release.aar directly inside the plugins directory.
Your AndroidManifest seems fine to me.

**Comment by mthnzbk** [comment]
worked. Thanks
