### ISSUE TITLE
Unable to load any ad

### ISSUE THREAD

**Issue by alt3r3dgd** [Shin-NiL/Godot-Android-Admob-Plugin#37]
**Godot version:** 3.2.1

**Admob Plugin version:** first happened in 3.0.0, but remains in 3.0.1

**Issue description:**

So, I tried to implement ads using this module, and... it didn't work. I followed all the instructions, ran my game on my phone via usb, and it just literally did nothing. The singleton did load, but neither banner nor rewarded ads didn't. The only thing that the signal says about the banner is "1". Is this solvable?

**Comment by Shin-NiL** [comment]
Please past here the logcat debug output as described in the troubleshooting section.

**Comment by MaaaxiKing** [comment]
I have the same problem. And the demo doesn't even start lol :/

**Comment by Shin-NiL** [comment]
The setup is a little tricky, so I recommend to first make the demo project to run because it's it I am able to compare.

Please redo all steps one by one, at the end run the adb logcat to catch any additional info.

**Comment by alt3r3dgd** [comment]
Sorry for not responding in a while, I'm having issues with Gradle (not being able to build my project), will respond as soon as I solve them.

**Comment by alt3r3dgd** [comment]
Alright, so I downloaded and set up the demo project, and it worked perfectly. Then I opened my game, but the issue still remains even after redownloading export templates and and android build template (I didn't forget to insert those two lines into AndroidManifest.conf). The logcat is **absolutely** silent.

**Comment by MaaaxiKing** [comment]
For me, the demo project doesn't even work. Could you maybe give more and clearer instructions in How to use?

**Comment by alt3r3dgd** [comment]
It is :eyes:

**Comment by MaaaxiKing** [comment]
Hmm then I have no clue why it isn't working. I just hope the next version will work perfectly and I hope Godot 3.2.2 will be released soon.

**Comment by alt3r3dgd** [comment]
Could it be not working for me because it's a child node of an autoloaded singleton?

**Comment by alt3r3dgd** [comment]
Aw, I am so poor... I forgot to enter the ad blocks ID's into the inspector. :facepalm: Still thanks for replying!

**Comment by MaaaxiKing** [comment]
I also don't understand why it prints "Admob Java Singleton not found", because if I make autoload the admob.gd script, in the script is "error(3,1): The class "Admob" conflicts with the AutoLoad singleton of the same name, and is therefore redundant. Remove the class_name declaration to fix this error." and in the Debugger: "Parser Error: The class "Admob" conflicts with the AutoLoad singleton of the same name, and is therefore redundant. Remove the class_name declaration to fix this error."

**Comment by alt3r3dgd** [comment]
If you get this error on PC, it's obvious - the module is for Android (it's literally said in the end of README). Otherwise I don't know.

**Comment by Shin-NiL** [comment]
>I also don't understand why it prints "Admob Java Singleton not found", because if I make autoload the admob.gd script, in the script is "error(3,1): The class "Admob" conflicts with the AutoLoad singleton of the same name, and is therefore redundant.

Did you check the 'Use Custom Build' option on the export menu?
Also, avoid using the same name on the autoload script, you can simply change your script to 'myAdmob' or any other name.

**Comment by MaaaxiKing** [comment]
Yes checked that. But I think I just did something wrong.
In the Explorer:
- project.godot:
```
; Engine configuration file.
; It's best edited using the editor UI and not directly,
; since the parameters that go here are not all obvious.
;
; Format:
;   [section] ; section goes between []
;   param=value ; assign values to parameters

config_version=4

_global_script_classes=[ {
"base": "Node",
"class": "Admob",
"language": "GDScript",
"path": "res://admob-lib/admob.gd"
} ]
_global_script_class_icons={
"Admob": "res://admob-lib/icon.png"
}

[android]

modules="org/godotengine/godot/GodotAdMob"

[application]

config/name="my Game Name"
run/main_scene="res://main.tscn"
config/icon="res://icon.png"
config/quit_on_go_back=false

[autoload]

SceneChanger="*res://Scenes/SceneChanger.tscn"
SL="*res://Scripts/Saver and Loader.gd"

[display]

window/stretch/mode="2d"
window/stretch/aspect="keep"

[rendering]

vram_compression/import_etc=true
environment/default_environment="res://default_env.tres"
```

- admob-lib
	- ...

- android
	- admob-plugin
		- AndroidManifest.conf
		```
		[application]
			<!-- Sample AdMob App ID: ca-app-pub-3940256099942544~3347511713 -->
			<meta-data
				android:name="com.google.android.gms.ads.APPLICATION_ID"
				android:value="myID"/>
		```

		- ...
	- build
		- gradle.properties
		```
		# Project-wide Gradle settings.
		
		# IDE (e.g. Android Studio) users:
		# Gradle settings configured through the IDE *will override*
		# any settings specified in this file.
		
		# For more details on how to configure your build environment visit
		# http://www.gradle.org/docs/current/userguide/build_environment.html
		
		# Specifies the JVM arguments used for the daemon process.
		# The setting is particularly useful for tweaking memory settings.
		org.gradle.jvmargs=-Xmx1536m
		
		# When configured, Gradle will run in incubating parallel mode.
		# This option should only be used with decoupled projects. More details, visit
		# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
		# org.gradle.parallel=true
		android.useAndroidX=true
		android.enableJetifier=true
		```

		- ...

	- ...

In Godot:
Project --> Project Settings --> Plugins: nothing
Project --> Project Settings --> General --> Compression --> Android: Modules:org/godotengine/godot/GodotAdMob
Project --> Export: 

- Android
- Android Ad (Runnable):
Options --> Custom Template --> Debug: C:/Users/my username/Documents/Spiele/Godot/my Game name/android/build/build/outputs/apk/debug/android_debug.apk
Options --> Custom Template --> Release: C:/Users/my username/Documents/Spiele/Godot/my Game name/android/build/build/outputs/apk/release/android_release.apk
Options --> Custom Template --> Use Custom Build: checkmark
Options --> Package --> Unqiue Name: my unique name
Options --> Package --> Name: my Game name
Options --> Permissions --> Access Network State: checkmark
Options --> Permissions --> Internet: checkmark
- iOS (Runnable)

Editor --> Editor Settings --> General --> Export --> Android --> Adb: C:/Users/my username/AppData/Local/Android/Sdk/platform-tools/adb.exe
Editor --> Editor Settings --> General --> Export --> Android --> Jarsigner: C:/Program Files/AdoptOpenJDK/jdk-8.0.252.09-hotspot/bin/jarsigner.exe
Editor --> Editor Settings --> General --> Export --> Android --> Debug Keystore: C:/Users/my username/debug.keystore
Editor --> Editor Settings --> General --> Export --> Android --> C:/Users/my username/AppData/Local/Android/Sdk


That's everything I changed. What is missing or wrong?

**Comment by Shin-NiL** [comment]
> By the way, I have also problems with exporting to Android using non-custom templates.

You should fix this first. Maybe you can get some support from the Godot help channels. I'm limited here to try to help just with this plugin issues.

**Comment by MaaaxiKing** [comment]
Alright, I fixed what was wrong with the normal export.
