### ISSUE TITLE
AdMob: onAdFailedToLoad -> ERROR_CODE_INTERNAL_ERROR / demo project

### ISSUE THREAD

**Issue by Tobi-La** [Shin-NiL/Godot-Android-Admob-Plugin#4]
**Godot version:**
Latest Master Daily Build ( v3.2.alpha.calinou.35944aebd )

**Issue description:**
Hey, I am new to admob godot and tried to run the demo project first.
Is it supposed to work out of the box or do I need to replace the adIds first?

I get the following errors when trying to run it on my device:

> 10-24 10:27:55.699 21246 21260 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
> 
> 10-24 10:27:55.745 21246 21260 I godot   : Godot Engine v3.2.alpha.calinou.35944aebd - https://godotengine.org
> 
> 10-24 10:27:55.756 21246 21260 I godot   : OpenGL ES 2.0 Renderer: Mali-T720
> 
> 10-24 10:27:55.787 21246 21260 I godot   :  
> 
> 10-24 10:27:56.226 21246 21260 E godot   : **WARNING**: Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
> 
> 10-24 10:27:56.226 21246 21260 E godot   :    At: scene/main/scene_tree.cpp:1252:_update_root_rect() - Font oversampling does not work in 'Viewport' stretch mode, only '2D'.
> 
> 10-24 10:27:56.255 21246 21260 D godot   : AdMob: init with content rating options
> 
> 10-24 10:28:07.208 21246 21246 W godot   : AdMob: onAdFailedToLoad -> ERROR_CODE_INTERNAL_ERROR
> 
> 10-24 10:28:07.209 21246 21246 W godot   : AdMob: callbackfunction -> _on_admob_banner_failed_to_load
> 
> 10-24 10:28:07.212 21246 21246 W godot   : AdMob: onRewardedVideoAdFailedToLoad. errorCode: 0
> 
> 10-24 10:28:07.218 21246 21246 W godot   : AdMob: onAdFailedToLoad(int errorCode) - error code: 0
> 
> 10-24 10:28:07.218 21246 21246 W godot   : AdMob: _on_interstitial_not_loaded
> 
> 10-24 10:28:07.219 21246 21260 I godot   : Error: Interstitial not loaded

**Comment by Shin-NiL** [comment]
The example project should work as is, without any modification (as it is working on my phone right now). Are you sure your phone has internet connection when testing?

**Comment by Tobi-La** [comment]
I'm so sorry, this is really embarrassing. You're right, somehow my phone had a connection problem. The app was the only thing i tested with this phone today, so I didn't realize it. I fixed it and your module is working just as expected. Sorry that i bothered you with that.

**Comment by Shin-NiL** [comment]
No prob ;)
