### ISSUE TITLE
Combine the coming new version with iOS

### ISSUE THREAD

**Issue by MaaaxiKing** [Shin-NiL/Godot-Android-Admob-Plugin#40]
If you want to export to both Android and iOS, it would be easier to download one plugin. If you either want to export to Android or to iOS you could also download the same plugin but not use the platform you're not exporting to. I pray this will be accepted.

**Comment by Shin-NiL** [comment]
The Godot new plugin system is exclusive for Android, it's not possible to work with iOS this same way. For that you need to use a thing called module, it's a little more complicated as you'll need to recompile the engine. Maybe you can open an issue on Godot repository asking for a similar plugin system for iOS, this way people can make it.

Another point is that I don't work with iOS, I don't have any Apple hardware or knowledge  to do that, so other people must do it.
