### ISSUE TITLE
show_interstitial() pauses code execution

### ISSUE THREAD

**Issue by EmEsA** [Shin-NiL/Godot-Android-Admob-Plugin#41]
**Godot version:**
3.2.2.rc2

**Admob Plugin version:**
3.0.1

**Issue description:**
When interstitial is shown the whole game script seem to pause.
I would want to show interstitial while I load some data via http request, but it doesn't seem to work that way.
When I close the interstitial right away the request is not yet completed so it manages to finish normally.
But when I wait for some time before closing. The request is failed when I finally do it.

**Comment by Shin-NiL** [comment]
Well, that's the expected behavior as the game goes to the background.

**Comment by EmEsA** [comment]
Thanks. I expected such an answer, but hoped there's a way to change it.
