### ISSUE TITLE
This is Future Funk Soccer Racing a game using your plug in!

### ISSUE THREAD

**Issue by KortexNinja** [Shin-NiL/Godot-Android-Admob-Plugin#42]
Hello there, my name is Freddy, I made this game and implemented ads using your amazing plug in! Wondering if you could put a link to it in your showcase section. 
Here's the link: https://play.google.com/store/apps/details?id=org.godotengine.cargame 

Thanks in advance man, I really appreciate it, and also thank you for the plugin it's been a game changer for me.

**Comment by Shin-NiL** [comment]
Thank you! It's because people like you that I keep running this project ;)

I sense a Road Fighter vibe there, I'll try your game for sure.
