### ISSUE TITLE
Add new game to showcase.md

### ISSUE THREAD

**Issue by cgeadas** [Shin-NiL/Godot-Android-Admob-Plugin#43]
Just released my new game, that includes this plugin.
I've mentioned this on the Credits. Is it possible to add my game to showcase.md?

The game is called Turzzle. And the link is:
https://play.google.com/store/apps/details?id=com.bananaonfire.turzzle

Thank you, and keep up the good work :-)

**Comment by bitmagine** [comment]
> Just released my new game, that includes this plugin.
> I've mentioned this on the Credits. Is it possible to add my game to showcase.md?
> 
> The game is called Turzzle. And the link is:
> https://play.google.com/store/apps/details?id=com.bananaonfire.turzzle
> 
> Thank you, and keep up the good work :-)

With the last version of Godot and the plugin?
I can't :(

**Comment by cgeadas** [comment]
@bitmagine When the last version of both came out, my game was already in a stage where I don't change anything (no new features, no upgrades to godot, plugins, macos, nothing). So, I'm using Godot 3.2.1 and Admob plugin 3.0.1. I wish you good luck.

**Comment by Shin-NiL** [comment]
@cgeadas Done! Thank you very much for the credits mention ;)

@bitmagine Could you open an issue describing with more details what's happening? Maybe we can help you.

**Comment by bitmagine** [comment]
> @cgeadas Done! Thank you very much for the credits mention ;)
> 
> @bitmagine Could you open an issue describing with more details what's happening? Maybe we can help you.

I got it!! Thank you very much
