### ISSUE TITLE
Issues implementing the plugin.

### ISSUE THREAD

**Issue by MossFrog** [Shin-NiL/Godot-Android-Admob-Plugin#44]
**Godot version: 3.2.2**

**AdMob Plugin version: 4.0.0**

**Issue description:**
I'm having issues getting ads to show when the compiled version is uploaded to a mobile device. I've checked the plugin box on the  export menu, i have imported the lib file successfully and can reference the node in GDScript, I have extracted the plugin to the plugins folder in the project under android and i have edited the XML file to include my app-id alongside the interstitial id within the editor but when i try to call a load_interstitial() nothing happens, neither do i get a failed to load error.

**Comment by MossFrog** [comment]
Allright so quick update, it seems like after moving the location of the app id metadata section in the XML file to the lower section it seems to now try to do something ill keep posting if i manage to solve the issue.

**Comment by MossFrog** [comment]
Okay turns out that i am getting an error code 0 when attempting to display the ad, i created the interstitial ad the day before so im curious what the issue might be? Also what does the ''Is Real'' checkbox do in the script variables?

**Comment by Shin-NiL** [comment]
You can use [test ads](https://developers.google.com/admob/android/test-ads) to know if your implementation is working.
You should set "Is Real" to on only on production builds, as it will display your real ads and you can be banned by Google if you click your own ad. When it's off, only test ads are displayed and you can use it for tests without ban risks.

**Comment by MossFrog** [comment]
After entering a test ad ID I receive an error code 1 and do not get any ad served

**Comment by MossFrog** [comment]
Could we maybe chat over discord?

**Comment by MossFrog** [comment]
Okay now its successfully entering the _on_AdMob_interstitial_loaded(): method, but i don't see anything visually is this normal?

**Comment by Shin-NiL** [comment]
> Okay now its successfully entering the _on_AdMob_interstitial_loaded(): method, but i don't see anything visually is this normal?

Yes, it's only loaded, you must call ```show_interstitial()``` to see the ad on the screen. I recommend you to first make the demo project to run to see how the things works.

**Comment by MossFrog** [comment]
Ah crap, i didn't know there was a display function my bad, i thought it was built into the load function. So sorry

**Comment by Shin-NiL** [comment]
Only banners ares displayed as soon as loaded.

**Comment by MossFrog** [comment]
This is a great plugin, you should push for it to be added into the android build template and Godot core, you already have the node library set up and a release version

**Comment by Shin-NiL** [comment]
Thank you my friend. Godot project doesn't accept proprietary code (AdMob). But I think the new plugin system is very good and modular, much better and user friendly than the old module system ;)

**Comment by MossFrog** [comment]
Way better, the old module system had its issues. It seems to serve the test ads just fine, ill try replacing them with real ones. Thanks for the help and the swift reply!

**Comment by MossFrog** [comment]
Still getting the error code 0 though with real ads, any ideas why? Google says there is a spin up time of about 2 hours but the ad was created yesterday so that shouldn't be the issue

**Comment by Shin-NiL** [comment]
By what some people says, sometimes it take much more time than expected. It's on Google's hands now.

**Comment by MossFrog** [comment]
Allright! Perfect thank you so much for the help and stay safe! Seems like Brazil is being hit hard by the corona virus

**Comment by Shin-NiL** [comment]
Thank you, stay safe too! Yeah, my country has been a real mess lately ;(
