### ISSUE TITLE
release build error code 3

### ISSUE THREAD

**Issue by MarcPhi** [Shin-NiL/Godot-Android-Admob-Plugin#46]
Godot version:
3.2.2.stable.official
AdMob Plugin version:
4.0.0
Issue description:
test ads working and showing, but in the release build no ads load (error code 3) 
(is_real is set to true)

**Comment by Shin-NiL** [comment]
As described in the README, there's not much we can do with this error, it could be many things on the Google side.
It's not this plugin related but, did you configure your [app-ads.txt](https://support.google.com/admob/answer/9363762)?

**Comment by MossFrog** [comment]
How do we configure app-ads.txt?

**Comment by Shin-NiL** [comment]
This is an AdMob thing, please check the documentation: https://support.google.com/admob/answer/9363762
