### ISSUE TITLE
Are location permissions necessary?

### ISSUE THREAD

**Issue by bitmagine** [Shin-NiL/Godot-Android-Admob-Plugin#49]
**Godot version:**
3.2.2 stable
**AdMob Plugin version:**
4.0.0

**Issue description:**
Are location permissions necessary for ads to be displayed in your language?

**Comment by bitmagine** [comment]
Please, excuse me my poor english, I'm spanish.

**Comment by Shin-NiL** [comment]
No, it's not.

**Comment by bitmagine** [comment]
Many advertisements appear to me in an unknown language, and I live in Spain.

**Comment by Shin-NiL** [comment]
I've never get this issue, I'm from Brazil and all ads served are in Portuguese, except the testing ones.
Maybe you can search AdMob about this.

**Comment by bitmagine** [comment]
Could it be because of this?

    admob.is_personalized=false

**Comment by bitmagine** [comment]
Changed property and now its works :)
