### ISSUE TITLE
Can you add my game to showcase?

### ISSUE THREAD

**Issue by bitmagine** [Shin-NiL/Godot-Android-Admob-Plugin#51]
**Godot version:**
3.2.2
**AdMob Plugin version:**
4.0.0
**Issue description:**
I released my first game on Google Play and includes your awesome plugin.
Is it possible to add my game to your showcase?

Piranha Escape (FREE):

https://play.google.com/store/apps/details?id=com.bitmagine.piranhaescape.free

Thank you and congratulations on your great work!

**Comment by Shin-NiL** [comment]
Thank you very much, game added, nice graphics ;)

**Comment by bitmagine** [comment]
Thanks to you ;)
