### ISSUE TITLE
Crashes while opening.

### ISSUE THREAD

**Issue by Swaraj-cs** [Shin-NiL/Godot-Android-Admob-Plugin#53]
**Godot version:**3.2.2

**AdMob Plugin version:** : https://github.com/Shin-NiL/Godot-Android-Admob-Plugin

**Issue description:**

Crashes while opening.
Able to create the custom build fine. After adding the admob plugin, it crashes while opening the game. 

Getting error 
Loading Android module: org/godotengine/godot/GodotAdMob
**ERROR**: Condition "!singletonClass" is true. Continuing.
At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.

In logcat the above message is displayed.

The added plugin is not listing in > Project settings > plugin.

Added the admob-lib in res://
res://admob-lib

Added admob-plugin in res://android/plugins
res://android/plugins/admob-plugin

**Comment by Shin-NiL** [comment]
Please, we need to know what plugin version are you using. Check the number on the release page https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/releases

**Comment by Swaraj-cs** [comment]
Releases 8
Version 4.0.0


Am a doing anything wrong with adding the files to folders??

- extract the content of the ```admob-plugin``` directory (```GodotAdmob.gdap``` and ```GodotAdmob.release.aar``` from the zip package) inside the ```res://android/plugins``` directory on your Godot project.

GodotAdmob.gdap``` and ```GodotAdmob.release.aar? what is this?

**Comment by Shin-NiL** [comment]
Unzip the file https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/releases/download/v4.0.0/GodotAdMobPlugin-4.0.0.zip
there you'll find a directory called admob-plugin, there you'll find these files.

**Comment by GAGANsinghmsitece** [comment]
yes, the game is crashing just after opening. I followed this tutorial:-
https://godotlearn.com/godot-3-2-how-to-integrate-google-ads-admob-for-android/
and your readme.md too. Nothing works.It didn't work with demo project too

**Comment by Shin-NiL** [comment]
Are you migrating from a Godot 3.2.1 project? If so, try to create a new one with 3.2.2 and test de demo or try [these tips](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/47).

**Comment by GAGANsinghmsitece** [comment]
I'm actually migrating from 3.1.2 but that game do not contain ads in previous version. I tried plugin with 3.2.2 with fresh project using demo directory of plugin. But stilll it crashes after installing

**Comment by Shin-NiL** [comment]
Do you still getting this error?

>Loading Android module: org/godotengine/godot/GodotAdMob
ERROR: Condition "!singletonClass" is true. Continuing.
At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.

if so, remove these lines
```
[android]
modules="org/godotengine/godot/GodotAdMob"
```

from the project.godot file, close the project, open it and try again.

**Comment by Swaraj-cs** [comment]
Hi, now the build is working fine .. But ads are not working .. am trying test ads. message is " AdMob Java Singleton not found" in adb logcat.

It worked only after removing modules="org/godotengine/godot/GodotAdMob" .. the app is not crashing. 

downloaded the files from 
https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/releases/download/v4.0.0/GodotAdMobPlugin-4.0.0.zip

**Comment by GAGANsinghmsitece** [comment]
I tried removing the line you mentioned but game still crashes, i'm uploading minimal project which would replicate the environment.

[demo.zip](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/4901365/demo.zip)
Please Cut plugin folder before installing android build templates.

**Comment by Shin-NiL** [comment]
> Hi, now the build is working fine .. But ads are not working .. am trying test ads. message is " AdMob Java Singleton not found" in adb logcat.

@Swaraj-cs Try redo these step:
on the Project -> Export... -> Android -> Options ->
- Plugins: turn on the Godot Ad Mob (this plugin)

>I tried removing the line you mentioned but game still crashes, i'm uploading minimal project which would replicate the environment.

@GAGANsinghmsitece the mentioned line stills there.
Open your project, go to Project -> Project Settings ->Android and delete the module entry with the value "org/godotengine/godot/GodotAdMob".
Save your project and try again.

**Comment by GAGANsinghmsitece** [comment]
Thanks now it's opening but no ad is showing. One thing i noticed is i cannot seem to get the plugin option in Project>Export>Android>Options
![image](https://user-images.githubusercontent.com/37043052/87166229-e21d6580-c2e8-11ea-8608-761d9d8efb76.png)
![image](https://user-images.githubusercontent.com/37043052/87166277-f2cddb80-c2e8-11ea-9a67-f48192299d46.png)

**Comment by Shin-NiL** [comment]
@GAGANsinghmsitece forget about the tutorial you cited before, it's not up to date, follow the instructions on the [README](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/main/README.md) file of this repository.

In special, this:

>extract the content of the admob-plugin directory (GodotAdmob.gdap and GodotAdmob.release.aar from the zip package) inside the res://android/plugins directory on your Godot project.

**Comment by GAGANsinghmsitece** [comment]
I'm not following the tutorial now. I got  "AdMob Java Singleton not found" because i'm unable to select the plugin in admob option. It looks like they moved the option in godot 3.2.2

**Comment by Swaraj-cs** [comment]
Hi, the app crashes in begining when the plugin is enabled from on the Project -> Export... -> Android -> Options ->

**Comment by GAGANsinghmsitece** [comment]
@Swaraj-cs  which godot version you are using?

**Comment by Swaraj-cs** [comment]
3.2.2

**Comment by GAGANsinghmsitece** [comment]
How did you activate the plugin i cannot find the option at project>export>options . Would be great if you can send a screenshot

**Comment by Swaraj-cs** [comment]
> How did you activate the plugin i cannot find the option at project>export>options . Would be great if you can send a screenshot

unzip the files.. https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/releases/download/v4.0.0/GodotAdMobPlugin-4.0.0.zip

Copy the files  GodotAdmob.gdap and GodotAdmob.release.aar from admob-plugin to res://android/plugins

dont paste the admob-plugin directory .. paste only the files.. After that you can see the plugin option below "custom  template"

**Comment by Swaraj-cs** [comment]
Hi Shin-NiL, 

 thank you so much. Forgot to edit the manifest file. Now its working and first ad loaded. Thank you .

GAGANsinghmsitece,
  Please update the manifest file. add 

<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>

for test..

:)

**Comment by GAGANsinghmsitece** [comment]
Now it works, thanks for help, you can close this issue now
