### ISSUE TITLE
Migrate GodotLib.calldeferred to emitSignal

### ISSUE THREAD

**Issue by ricardoalcantara** [Shin-NiL/Godot-Android-Admob-Plugin#55]
**Godot version:**
Godot 3.2.2 Stable

**AdMob Plugin version:**
Master

**Issue description:**

It seems like Godot has a bug that it cannot calldeferred when using C# Mono classes, I opened an Issue https://github.com/godotengine/godot/issues/40481 but I was checking the Google Payment Billing implementation and they use Signals, which not only works with C# but also looks a better implementation for me. I have made those changes in my fork
https://github.com/ricardoalcantara/Godot-Android-Admob-Plugin/commit/b557e134fd8dc1185d448ab0b3c3f28f3f1595ac I tested and worked correctly to me, if you feel like accepting a Pull Request with these changes I can request it.

**Comment by Shin-NiL** [comment]
Very nice work bro, is that working fine? I saw you opened[ this issue](https://github.com/godotengine/godot/issues/40527). I'll have to update my gdscript binding and documentation, as seems like you added a new method to Banners.

If is everything else working like before, please open an PR as the code is much better for long term.

**Comment by ricardoalcantara** [comment]
Everything's working fine so far, besides the breaking change and this issue which doesn't break the game and happens only with C#, but using the other way the callback does's work at all, This issue was accepted as bug and probably will be fixed anytime soon.

I added two methods: Move to add the ability to move the banner without the reload it, and I change one behavior: In Banners constructor there was this code:

```java
 if (adView != null) {	
            layout.removeView(adView); // Remove the old view	
        }
```

which adView was always null and when I was doing loadBanner() to changing the location is was leaving, sometimes, the old banned hanging.

I will update the demo and I will open a PR then!

Thanks.

**Comment by ricardoalcantara** [comment]
Resolved with PR https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/pull/56
