### ISSUE TITLE
Ads are not loading

### ISSUE THREAD

**Issue by dbrova15** [Shin-NiL/Godot-Android-Admob-Plugin#58]
**Godot version:**
3.2.2
**AdMob Plugin version:**
4.0
**Issue description:**

Ads are not loading.

![изображение](https://user-images.githubusercontent.com/20703983/88405639-3d1a8680-cdd8-11ea-9131-3fea59049c60.png)
![изображение](https://user-images.githubusercontent.com/20703983/88405786-6affcb00-cdd8-11ea-8783-67c941c2a469.png)

When the main scene is loaded, the loader is shown to me, I check if there is an Internet connection, if not, we load the game interface, if there is, we do the following: the admob.load_interstitial () command is called. Then a timer starts, which tries to show the ad every half second. After the user closes the ad, the main stage interface is displayed and the timer stops. But since the Internet is there and ads are not loading, I see the loader endlessly.

On Godot version 3.2.1 and with the old plugin system, everything works well.

**Comment by Shin-NiL** [comment]
Did you update the admob-lib directory to 4.0.0? You say you're using the 4.0.0, but in the screenshot the node name is "Admob" but in 4.0.0 it was changed to "AdMob".

**Comment by dbrova15** [comment]
Yes! It works! I upgraded from version 3.2.1 and did not change the admob-lib folder. But now everything works. Thank!
