### ISSUE TITLE
Changing banner state

### ISSUE THREAD

**Issue by Themaker482** [Shin-NiL/Godot-Android-Admob-Plugin#6]
**Godot version: 3.2**

**when var "isReal" is set to true**
This is not an issue but a doubt, when i try changing the var "isReal to true, the buttons to test the ads dont change their state to enabled, I assumed that is because the ad is not loaded, has anyone tried to display real ads?

**Comment by Shin-NiL** [comment]
Maybe same issue as #5?

**Comment by Themaker482** [comment]
Yes, it seem that is due to the lack of inventory ads in admob, I will use mediation to have more ads in my app, thanks a lot!!!!
