### ISSUE TITLE
Didn't find class "org/godotengine/godot/GodotAdMob"

### ISSUE THREAD

**Issue by NoobCIT** [Shin-NiL/Godot-Android-Admob-Plugin#60]
**Godot version:**
Godot_v3.2.2-stable_win64

**AdMob Plugin version:**
Version 4.0.0

**Issue description:**

I clicked the android icon in Godot to deploy my game to my phone.  After it finishes, the game opens on my phone and says "stopped working" and closes.  It just keeps crashing.

For your information, my game deploys to my phone just fine before I added the Admob plugin.  I am able to deploy to my phone and play my game with no issues.  The problem only occurs after I try using the Admob plugin.  I also can't get the demo to work and can't get any test ads to show up.  Nothing seems to work when it comes to the Admob plugin.

I tried to follow the directions by Shin-NiL and it didn't work.  I was following the 3.2 AdMob Tutorial: https://godotlearn.com/godot-3-2-how-to-integrate-google-ads-admob-for-android/

Project.godot:
![image](https://user-images.githubusercontent.com/25425914/88488647-79b6c100-cf43-11ea-8e57-983d1d7237cd.png)

Export:
![image](https://user-images.githubusercontent.com/25425914/88488661-994de980-cf43-11ea-81fe-f3d9567e2b95.png)

Plugins:
![image](https://user-images.githubusercontent.com/25425914/88488686-c13d4d00-cf43-11ea-8520-e1d861bab812.png)

AndroidManifest.xml
![image](https://user-images.githubusercontent.com/25425914/88488794-6bb57000-cf44-11ea-9435-7685a2fd98ef.png)

Any direction or help would be much appreciated.  I'm also a noob programmer, so dumbing things down would be helpful. 
 Thanks.

**Comment by Shin-NiL** [comment]
Try removing this  from project.godot, it's not needed anymore and the app will crash if present:
> Project.godot:
![image](https://user-images.githubusercontent.com/25425914/88488647-79b6c100-cf43-11ea-8e57-983d1d7237cd.png)

The mentioned tutorial is outdated, please just follow this repository readme file.

**Comment by NoobCIT** [comment]
Thanks for the reply.  Unfortunately, that didn't work either.  I still get the same error.

![image](https://user-images.githubusercontent.com/25425914/88601369-5f551400-d025-11ea-8d9b-98a719cdb5ad.png)

I understand you are busy, but I just wanted to bring it to your attention.  I'll try to figure out another work around.  Thanks.

**Comment by Shin-NiL** [comment]
I'm sorry if I looked rude, it was not my intention.

If the error persists take a look if the android module configuration on the project.godot was saved. [Users mentioned that it still present on some cache.](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/47)
