### ISSUE TITLE
Singleton question

### ISSUE THREAD

**Issue by dhruv866** [Shin-NiL/Godot-Android-Admob-Plugin#61]
**Godot version:**
3.2.2
**AdMob Plugin version:**
4.0
**Issue description:**
I just want to ask that can we use the script of admob as global script so that we put it in autoload
Please tell its a personal request to you
Bless you

**Comment by Shin-NiL** [comment]
Yes, you can, not the admob.gd file, but you can instantiate an AdMob node, set the properties and call its methods via code on a global autoload.
 
In fact I consider this the best approach. The plugin is a singleton by itself, so it makes sense to have a single access point to it.

**Comment by dhruv866** [comment]
So thanks of you for replying
