### ISSUE TITLE
[ASK] my Godot Ad Mob options not showing

### ISSUE THREAD

**Issue by mangbuda** [Shin-NiL/Godot-Android-Admob-Plugin#65]
**Godot version: 3.2.2**

**AdMob Plugin version:4.0**

**Issue description:**
i have issue "AdMob Java Singleton not found:", but my export did't sow  Godot Ad Mob options, i had delete and add it again, but  Godot Ad Mob options still not showing.

![missing](https://user-images.githubusercontent.com/51502904/89107354-b65e4d00-d45a-11ea-9ecd-ed69b185b240.png)

**Comment by Shin-NiL** [comment]
Check if the `GodotAdmob.gdap` and `GodotAdmob.release.aar` are inside the `res://android/plugins` directory:

`res://android/plugins/GodotAdmob.gdap`
`res://android/plugins/GodotAdmob.release.aar`

**Comment by mangbuda** [comment]
aww, thanks ...
