### ISSUE TITLE
Ads won't load

### ISSUE THREAD

**Issue by Abb1x** [Shin-NiL/Godot-Android-Admob-Plugin#66]
**Godot version:3.2.2**

**AdMob Plugin version: 4.0**

**Issue description**:The ads won't load, here's adb logcat output:
![image](https://user-images.githubusercontent.com/54687179/89188256-67a0d800-d56c-11ea-9380-afc073553772.png)

I got a bunch of errors,I used the demo to test it 
sorry for bothering you

**Comment by Shin-NiL** [comment]
The demo from the main branch will not work with 4.0.0 release. You should download the source code (including demo) from the 4.0.0 release.

If you cloned this repository, do checkout on this version or download the zip [here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/archive/v4.0.0.zip).

**Comment by Abb1x** [comment]
OK it works,but I got this error message: onAdFailedToLoad() errorCode: 0

**Comment by Shin-NiL** [comment]
Do you have internet connection on your device?

**Comment by lentsius-bark** [comment]
Also I once got a code 0 I believe when trying my test ads without having set up payment information in my admob account.

**Comment by Abb1x** [comment]
> Also I once got a code 0 I believe when trying my test ads without having set up payment information in my admob account.

Okay so I have to set up a payment method even with google test ads?

**Comment by lentsius-bark** [comment]
Yes, that's how I got mine to work. It took a day or so for it to activate too.

**Comment by Abb1x** [comment]
> Yes, that's how I got mine to work. It took a day or so for it to activate too.
> 
> EDIT: as mentioned in #52 , you can in the meantime make use of google's own test ad codes over here: [Google test ads](https://developers.google.com/admob/android/test-ads)

I'm using the test ads code, I need a payment method even for that?

**Comment by Shin-NiL** [comment]
@Abb1x 
> I'm using the test ads code, I need a payment method even for that?

No, it should work as is.

Did you see my previous question about the internet connection on your device?

**Comment by Abb1x** [comment]
> @Abb1x 
> > I'm using the test ads code, I need a payment method even for that?
> 
> No, it should work as is.
> 
> Did you see my previous question about the internet connection on your device?
> 
> 

Yes I got internet connection and I added it in permissions

**Comment by Shin-NiL** [comment]
Please check if the ad codes are correct, I have no no other idea beside this.

**Comment by Abb1x** [comment]
> Please check if the ad codes are correct, I have no no other idea beside this.

They are, I'll try to find a fix and send it here

**Comment by MasterOX47856** [comment]
i get the same error pls help

**Comment by Abb1x** [comment]
I got an adblock, do you think that might be it?

**Comment by Shin-NiL** [comment]
> I got an adblock, do you think that might be it?

Most likely.

**Comment by MasterOX47856** [comment]
I dont have one and it's not working

**Comment by Shin-NiL** [comment]
@MasterOX47856 are you getting error code 0? If not, please open a new issue describing you issue with full details.

**Comment by MasterOX47856** [comment]
I am getting error code 0

**Comment by Shin-NiL** [comment]
@MasterOX47856 are you testing the demo project too?

**Comment by MasterOX47856** [comment]
I saw the code

**Comment by Abb1x** [comment]
Deactivated the Adblocker, still not working and same error, should I try a previous release?

**Comment by Shin-NiL** [comment]
I'm really sorry, but I have no idea what's causing this issue. Release 4.0.0 is working fine to me and other users, maybe we are missing something in the process.

**Comment by Abb1x** [comment]
> I'm really sorry, but I have no idea what's causing this issue. Release 4.0.0 is working fine to me and other users, maybe we are missing something in the process.

Do you want me to send my project?

**Comment by Abb1x** [comment]
The plugin isn't appearing in the plugins tab tho

**Comment by Shin-NiL** [comment]
> Do you want me to send my project?

Yes, please.

**Comment by Abb1x** [comment]
there you go:
https://www.swisstransfer.com/d/41015056-01a5-43d9-85ac-de437f749184

**Comment by Shin-NiL** [comment]
Tested your project, just worked:

![image](https://user-images.githubusercontent.com/4077589/90129541-3760f280-dd3f-11ea-9eca-b8b7ea4b9fdc.png)

**Comment by Abb1x** [comment]
It works! Thanks, I guess the adblock was the problem, thank you for your time! ![Screenshot_20200825-185025.png](https://user-images.githubusercontent.com/54687179/91235657-fcc66500-e703-11ea-8783-1bf229957cee.png)
