### ISSUE TITLE
Is it possible to compile the plugin with an android custom export template?

### ISSUE THREAD

**Issue by Kolgolar** [Shin-NiL/Godot-Android-Admob-Plugin#67]
**Godot version: 3.2.2**

**AdMob Plugin version: 4.0.0**

**Issue description:**

I'm trying to reduce apk size of my project so for that I compile custom export templates, but I don't know how to add last version of AdMob to it.
It was possible when AdMob was presented as module, but I didn't find any information about how to do it with the new plugin system.
Is there a way to do this?

**Comment by Shin-NiL** [comment]
I've never tried before, in theory it should work.

Maybe I'm wrong, but as far as I understand when you use "Use Custom Build" option the export templates are not used, the contents of the file `android_source.zip` are used instead. You should find a way to create this zip file with your custom build and then use it (maybe maybe overwriting it on the template install directory on your machine).

Anyways, it's a good question to be opened on the Godot repository.

**Comment by Kolgolar** [comment]
Thank you for the answer!
You was right, `Use Custom Build` option forces engine use `android_source.zip`, BUT it also uses `godot-lib.release.aar`. So I had to replace this files with manual compiled ones and everything seems to be okay now.
