### ISSUE TITLE
Using my own ID doesn't work

### ISSUE THREAD

**Issue by Coldragon** [Shin-NiL/Godot-Android-Admob-Plugin#7]
**Godot version:3.2.beta2**

**Issue description:**
When I use my own Ad ID from admob the `loadInterstitial(adInterstitialId)` doesn't work and I have an `_on_interstitial_not_loaded` that is triggered. Same problem with banner and reward.

I test tried it with the demo project and my own game and it only work with the dummy id google provide.

I tried to add my App ID in the manifest but I think it wasn't necessary and it still don't work.

Am I missing something ?

**Comment by Coldragon** [comment]
I made an example project in android studio and I get onAdFailedToLoad() error 3 and after research it look like there is no avaiable ads for me to display (or because i'm not in production ?)

**Comment by Shin-NiL** [comment]
It's a common issue, please check https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/5

**Comment by Coldragon** [comment]
Thank's
