### ISSUE TITLE
game crashs in android when export with enable Godot Ad Mob

### ISSUE THREAD

**Issue by Mohammed-Anwar** [Shin-NiL/Godot-Android-Admob-Plugin#71]
**Godot version:**

**AdMob Plugin version:**

**Issue description:**
first sorry for any bad English 
so i just make a demo project to test the plugin and how it works
I follow the steps in this [page](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin)
then when i export the game using one click display 
the game installed but it's crash whine opening it
it test a lot of things but the only thing that I am sure about
is when I enable the "Godot Ad Mob" in android export UI the game gets the crash issue 
but if i disable it the game works fine but also without any ADs

I'm using Godot 3.2.2

**Comment by Shin-NiL** [comment]
Did you edit the AndroidManifest.xml adding the App ID? You can see how it should be for the demo[ here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/issues/45).

When the app crashes you can get some useful information using Android logcat.

**Comment by Mohammed-Anwar** [comment]
yap
know after some debug I discovered that i changed the android:name to my ad app name :/
after reuse yours the game works fine without any problem 
thx and sorry for wasting your time :)
