### ISSUE TITLE
Possible to disable button if interstitial is not loaded?

### ISSUE THREAD

**Issue by thermocoffee** [Shin-NiL/Godot-Android-Admob-Plugin#74]
**Godot version:**
3.2.2

**AdMob Plugin version:**
4.0.0

**Issue description:**

I was wondering if you could help me. Thank you so much for the work you put into this plugin. I have admob setup to show an interstitial ad when the user loses the game and clicks on a button "try again". Then when the user closes the interstitial ad, the game restarts. Works flawlessly! but my issue is if the user doesn't have internet, the interstitial ad never shows up so there's no way for the user to start the game over since the code is waiting for the interstitial ad to be closed. So is it possible to disable a button if the interstitial ad is not loaded? This way, the button underneath it can activate and let the user restart the game. 

I'm not sure if this is the correct way to do it. I've only been using godot for about a week.

Thanks so much!

**Comment by Shin-NiL** [comment]
You can use the method `is_interstitial_loaded()` to check if the ad was loaded, if not loaded you can do whatever you want, disable a button, start a new lvl etc.

**Comment by thermocoffee** [comment]
> You can use the method `is_interstitial_loaded()` to check if the ad was loaded, if not loaded you can do whatever you want, disable a button, start a new lvl etc.

Great! Thank you!
