### ISSUE TITLE
Game published on Play Store with ads working thanks to this plugin

### ISSUE THREAD

**Issue by wynoo** [Shin-NiL/Godot-Android-Admob-Plugin#76]
**Godot version:** 3.2.2

**AdMob Plugin version:** 4.0.0

**Issue description:**
I released a game that includes this fantastic plugin.
Is it possible to add my game to showcase.md?

It is called Zeptris, and the link is:

https://play.google.com/store/apps/details?id=net.wynoo.zeptris

Thank you so much and congratulations

**Comment by Shin-NiL** [comment]
Thank you very much! Game added to the showcase as requested, congrats for publishing ;)
