### ISSUE TITLE
Low ad Impression. 

### ISSUE THREAD

**Issue by superRaptor911** [Shin-NiL/Godot-Android-Admob-Plugin#77]
**Godot version:**
  3.2.2
**AdMob Plugin version:**
4.0 , 3.x

**Issue description:**
Thank you shin-nil for making this plugin. It works perfectly fine and is easy to use but my impressions are low, its about 10% and My match rate is between 80 -90 %. Maybe my usage is wrong.

I am loading Admob in a singleton script and using it globally.

**Comment by Shin-NiL** [comment]
Did you [setup an app-ads.txt](https://support.google.com/admob/answer/9363762) file on your website?

**Comment by superRaptor911** [comment]
No

**Comment by Shin-NiL** [comment]
I was having similar issue with my apps recently and was solved after I created this file.

**Comment by superRaptor911** [comment]
Thank you, i will try but why this works?

**Comment by superRaptor911** [comment]
Created the file.

**Comment by Shin-NiL** [comment]
It usually takes a while to take effect, let's wait.
