### ISSUE TITLE
app crushes

### ISSUE THREAD

**Issue by samordoch** [Shin-NiL/Godot-Android-Admob-Plugin#79]
**Godot version:** 3.2.2

**AdMob Plugin version:** 4

**Issue description:**
when i try to open the game on an android device the game closed
i tried to follow your old resolved issues that are all sums up in not updating the manifest
i did update it and still getting crushes i disabled the  :
org/godotengine/godot/GodotAdMob 
and the app did launch but no ads on demo or mine app

[manifest.zip](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/5180052/manifest.zip)

i added the xml and export to the zip

**Comment by Shin-NiL** [comment]
The AndroidManifest seems ok to me. You should use `logcat` to get more detailed information.

**Comment by samordoch** [comment]
Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider

**Comment by samordoch** [comment]
this is what i am getting on log cat a lot of admob not set up correctly

**Comment by Shin-NiL** [comment]
Try to add the metadata in the manifest exactly as in the readme file:

```
        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>
```
first android:name and after android:value

**Comment by samordoch** [comment]
![Screenshot_20200906-215216_Logcat Reader](https://user-images.githubusercontent.com/61991734/92333103-845c8e00-f08b-11ea-9846-dd8609211bb4.jpg)
Found this error on the logcat

**Comment by Shin-NiL** [comment]
Remove the `org/godotengine/godot/GodotAdMob` from the `project.godot` file.

**Comment by samordoch** [comment]
Without it the app does work but no ads show when click on buttons in demo scene

**Comment by Shin-NiL** [comment]
Again,  use `logca`t to get more detailed information.

**Comment by samordoch** [comment]
i am attaching the logcat just notify that i deleted the line in the settings because  when i delete on the file godot add it again when exporting
[logcat_09-07-2020_12-26-53.txt](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/5182309/logcat_09-07-2020_12-26-53.txt)

**Comment by Shin-NiL** [comment]
```
[09-07 12:25:39.233 26439:26439 W/godot]
AdMob: onAdFailedToLoad. errorCode: 0

[09-07 12:25:39.253 26439:26439 W/godot]
AdMob: onAdFailedToLoad(int errorCode) - error code: 0

[09-07 12:25:39.269 26439:26439 W/godot]
AdMob: onRewardedVideoAdFailedToLoad. errorCode: 0
```

You are getting [error code 0](https://support.google.com/admob/thread/3494603), check if the ad IDs are correct.

**Comment by samordoch** [comment]
i am trying to start your demo scene by using google test ads double check 
![image](https://user-images.githubusercontent.com/61991734/92395969-e7eac800-f12c-11ea-9bdc-318f57c8dd41.png)
https://developers.google.com/admob/android/test-ads
still getting the same error 
[logcat_09-07-2020_17-18-11.txt](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/files/5183510/logcat_09-07-2020_17-18-11.txt)

if you have time i can connect with you via zoom or disqord and give you control to see all the project settings

**Comment by Shin-NiL** [comment]
My advice is to start over the demo project from zero. All test ids are configured there, you just need to add the App ID on the AndroidManifest.

**Comment by samordoch** [comment]
> My advice is to start over the demo project from zero. All test ids are configured there, you just need to add the App ID on the AndroidManifest.

**UPDATE**
i tried to do all the installation again but with my own ads id and using the module again no the app is crushing but i am receiving those errors:
09-07 17:32:22.538 12087 12187 I godot   : Godot Engine v3.2.2.stable.official - https://godotengine.org
09-07 17:32:22.550 12087 12187 I godot   : OpenGL ES 3.0 Renderer: Mali-G71
09-07 17:32:22.618 12087 12187 I godot   :
09-07 17:32:23.119 12087 12187 D godot   : AdMob: init with content rating options
09-07 17:32:23.120 12087 12187 D godot   : AdMob: init with content rating options
09-07 17:32:35.201 12087 12087 W godot   : AdMob: onRewardedVideoAdFailedToLoad. errorCode: 0
09-07 17:32:35.210 12087 12087 W godot   : AdMob: onAdFailedToLoad. errorCode: 0
09-07 17:32:35.216 12087 12087 W godot   : AdMob: onAdFailedToLoad(int errorCode) - error code: 0
09-07 17:33:39.360 13375 13504 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
09-07 17:33:39.361 13375 13504 E godot   : **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
09-07 17:33:39.361 13375 13504 E godot   :    At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
--------- beginning of system
09-07 17:33:57.100 13715 13739 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
09-07 17:33:57.101 13715 13739 E godot   : **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
09-07 17:33:57.101 13715 13739 E godot   :    At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
09-07 17:33:59.284 13774 13794 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
09-07 17:33:59.284 13774 13794 E godot   : **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
09-07 17:33:59.284 13774 13794 E godot   :    At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.
09-07 17:37:00.657 14670 14695 E godot   : **ERROR**: Remote Debugger: Unable to connect. Status: 3.
09-07 17:37:00.657 14670 14695 E godot   :    At: scene/debugger/script_debugger_remote.cpp:95:connect_to_host() - Remote Debugger: Unable to connect. Status: 3.
09-07 17:37:00.676 14670 14695 I godot   : Loading Android module: org/godotengine/godot/GodotAdMob
09-07 17:37:00.678 14670 14695 E godot   : **ERROR**: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
09-07 17:37:00.679 14670 14695 E godot   :    At: platform/android/java_godot_lib_jni.cpp:104:_initialize_java_modules() - Condition "!singletonClass" is true. Continuing.

**Comment by Shin-NiL** [comment]
> ERROR: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.

Don't put this on the project options, create a new project and follow strictly the readme instructions, don't follow third-party tutorials, as they are out of date.

**Comment by samordoch** [comment]
> > ERROR: Couldn't find singleton for class: org/godotengine/godot/GodotAdMob.
> 
> Don't put this on the project options, create a new project and follow strictly the readme instructions, don't follow third-party tutorials, as they are out of date.

Did all opened the demo.godot directly no the app loads no errors but ads don't work
I am not getting to error 0 again
The reload button does nothing
![Screenshot_20200907-210002_AdMob Plugin Test.jpg](https://user-images.githubusercontent.com/61991734/92410794-f0072f80-f14d-11ea-92a7-2c0b2cad5832.jpg)

**Comment by Shin-NiL** [comment]
```
[09-07 20:58:50.703 12621:12621 W/godot]
AdMob: onRewardedVideoAdFailedToLoad. errorCode: 0

[09-07 20:58:50.742 12621:12621 W/godot]
AdMob: onAdFailedToLoad. errorCode: 0

[09-07 20:58:50.761 12621:12621 W/godot]
AdMob: onAdFailedToLoad(int errorCode) - error code: 0

[09-07 20:58:50.771 12621:12621 W/godot]
AdMob: onAdFailedToLoad. errorCode: 0

[09-07 20:58:50.776 12621:12621 W/godot]
AdMob: onAdFailedToLoad(int errorCode) - error code: 0
```

You do still getting error code 0.

**Comment by samordoch** [comment]
OK I got it the problem was my rooted device has adblocker I canceled it and now it works

**Comment by Kamyabnz** [comment]
This should get closed I think 😅
