### ISSUE TITLE
Fixing README

### ISSUE THREAD

**Issue by RustyStriker** [Shin-NiL/Godot-Android-Admob-Plugin#8]
README is missing the need to set the internet and Access internet state to true.

**Comment by Shin-NiL** [comment]
It's not needed anymore. You can't even find any mention to that on the Admob documentation. Are having any trouble with that?

**Comment by RustyStriker** [comment]
It didn't work without those permissions for me

**Comment by Shin-NiL** [comment]
What's your Android version?

**Comment by RustyStriker** [comment]
9.0, im using miui 11 on redmi note 7
