### ISSUE TITLE
New url

### ISSUE THREAD

**Issue by bitmagine** [Shin-NiL/Godot-Android-Admob-Plugin#80]
**Godot version:**
3.2.2 
**AdMob Plugin version:**
4.0.0 
**Issue description:**
Please, can you change url for Piranha Escape on Showcase? I have removed that version from Google Play.
New url:
https://play.google.com/store/apps/details?id=com.bitmagine.piranhaescape

**Comment by Shin-NiL** [comment]
Done.

**Comment by bitmagine** [comment]
Thanks!! 😉
