### ISSUE TITLE
**ERROR**: In Object of type 'JNISingleton' 

### ISSUE THREAD

**Issue by osimuka** [Shin-NiL/Godot-Android-Admob-Plugin#84]
**Godot version: 3.2.2**

**AdMob Plugin version: 4.0.0**

**Issue description:**

I get the error message ```**ERROR**: In Object of type 'JNISingleton': Attempt to connect nonexistent signal 'on_interstitial_failed_to_load' to method 'Node._on_interstitial_failed_to_load'.``` 
```Invalid call. Nonexistent function 'initWithContentRating' in base 'JNISingleton'.```
When running on android devices for testing.

**Comment by Shin-NiL** [comment]
Are you testing the demo project?

If you're using 4.0.0 you should use the 4.0.0 demo project too, not the one one the main branch of this repository.

**Comment by osimuka** [comment]
I just plugged it in directly into my application 😅 

But I sorted the issue now.

Solution:
#### Godot version: 3.2.2
#### AdMob Plugin version: 4.1.1

The problem I suspect was fixed my the introduction of the java signals 🚀
