### ISSUE TITLE
AndroidManifest.xml is overwritten during build

### ISSUE THREAD

**Issue by CngKO** [Shin-NiL/Godot-Android-Admob-Plugin#85]
**Godot version:**
3.2.3 stable

**AdMob Plugin version:**
4.1.1

**Issue description:**

When running game on Android phone through the Godot Editor, AndroidManifest.xml is overwritten, deleting the line where we set:
<meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-3940256099942544~3347511713"/>

Game crashes at start up, probably due to the manifest file being overwritten

**Comment by Shin-NiL** [comment]
Put your data just below the code

```
<!-- Custom application XML added by add-ons. -->
<!--CHUNK_APPLICATION_BEGIN-->
<!--CHUNK_APPLICATION_END-->
```

If you put it between these lines, it will be deleted.

**Comment by CngKO** [comment]
Thank you, @Shin-NiL.  It works now.  Placing the meta-data tag with the application ID as follows solved the issue:

```
<!-- Custom application XML added by add-ons. -->
<!--CHUNK_APPLICATION_BEGIN-->
<!--CHUNK_APPLICATION_END-->

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-1150000000100009~9000000004"/>
```
