### ISSUE TITLE
Very slow apk compile time

### ISSUE THREAD

**Issue by nikhilCad** [Shin-NiL/Godot-Android-Admob-Plugin#87]
**Godot version:**
3.2.2

**AdMob Plugin version:**
4.1.1

**Issue description:**

Its been 10 minutes and the app just keeps on compiling. It is extremely slow. What can be done to speed it up??

**Comment by Shin-NiL** [comment]
For me it took longer just the first time because gradle downloads the dependencies and do a full compile. After that it is much faster. If you're on the first compilation, maybe your internet speed is too slow.

**Comment by nikhilCad** [comment]
Hmm ok thank you

**Comment by nikhilCad** [comment]
Can you please tell the size of downloads??

**Comment by Shin-NiL** [comment]
Sorry, but I don't know the size, because it's all downloaded behind de scenes. Are you still unable to do the first compilation?

**Comment by nikhilCad** [comment]
Done!!!! Finally. I am replying u through email so can u close this issue
yourself pls.

**Comment by nikhilCad** [comment]
If anyone stumbles upon this in future, the download was about 800 MB for me
