### ISSUE TITLE
Published my game using this plugin on Google Play.

### ISSUE THREAD

**Issue by hideckies** [Shin-NiL/Godot-Android-Admob-Plugin#90]
**Godot version:** 3.2.2

**AdMob Plugin version:** 4.1.1

**Issue description:**
Thanks to this plugin, I was able to display AdMob.

The name of this game is **"Landbox"** .

The link is following:
[https://play.google.com/store/apps/details?id=org.hideckies.landbox](https://play.google.com/store/apps/details?id=org.hideckies.landbox)

I would like to thank you again:)

**Comment by Shin-NiL** [comment]
Just added to the showcase.
Your game has an interesting concept, I will download it for sure.

Thank you very much. Knowing the games published with this plugin makes me happy.
