### ISSUE TITLE
How to remove test ads Im using admob shin-nil plugin.. Thank you

### ISSUE THREAD

**Issue by jingMV** [Shin-NiL/Godot-Android-Admob-Plugin#91]
**Godot version:3.2.2**

**AdMob Plugin version:4.1.1**

**Issue description:**
In my interstitial ads, there was a test ads showing in the top

how to remove it? Thank you

**Comment by Shin-NiL** [comment]
Turn on the "Is Real" variable on the AdMob node inspector or set  the `is_real` property to `true`  on the code.

**Comment by Kamyabnz** [comment]
@Shin-NiL Hi, i will be using your plugin in my upcoming game, still working on my UI.
When it is done and out there, i will let you know. 

Hope it gets some downloads, if it does that sponsor button is going to be clicked by me gladly mate 🤣👌

**Comment by Shin-NiL** [comment]
@Kamyabnz good luck with your project my friend, let us update our showcase when it's done.

> Hope it gets some downloads, if it does that sponsor button is going to be clicked by me gladly mate 🤣👌

Thank you!

**Comment by jingMV** [comment]
> 
> 
> Turn on the "Is Real" variable on the AdMob node inspector or set the `is_real` property to `true` on the code.

I will try it thank you

**Comment by jingMV** [comment]
> 
> 
> Turn on the "Is Real" variable on the AdMob node inspector or set the `is_real` property to `true` on the code.

its not working to me mate

**Comment by Shin-NiL** [comment]
@jingMV are you sure you're using your own interstitial ad id and app id and not the testing ones?

**Comment by jingMV** [comment]
> 
> 
> @jingMV are you sure you're using your own interstitial ad id and app id and not the testing ones?

yes mate,
the banner and rewarded video is not implement in my codes. I'm only using the interstitial ads.
and then My admob metric is running but ads not showing to them. 

here is my metric now:
Sessions / user: 2.3
Avg. session duration: 1m 55s
Ad exposure / session: 3.31%
Active users: 20

**Comment by Shin-NiL** [comment]
The only part on the code where test devices are added is [here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/8d9c1f68822b59a92fb5a0fa7753ecd2dd2c46d9/admob-plugin/godotadmob/src/main/java/shinnil/godot/plugin/android/godotadmob/GodotAdMob.java#L154). If isReal is false it should not display test ads at all. I don't know what could be causing this issue...

**Comment by jingMV** [comment]
> 
> 
> The only part on the code where test devices are added is [here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/8d9c1f68822b59a92fb5a0fa7753ecd2dd2c46d9/admob-plugin/godotadmob/src/main/java/shinnil/godot/plugin/android/godotadmob/GodotAdMob.java#L154). If isReal is false it should not display test ads at all. I don't know what could be causing this issue...

okay mate,
I will double check my codes again, tnx

**Comment by jingMV** [comment]
> The only part on the code where test devices are added is [here](https://github.com/Shin-NiL/Godot-Android-Admob-Plugin/blob/8d9c1f68822b59a92fb5a0fa7753ecd2dd2c46d9/admob-plugin/godotadmob/src/main/java/shinnil/godot/plugin/android/godotadmob/GodotAdMob.java#L154). If isReal is false it should not display test ads at all. I don't know what could be causing this issue...

hello mate, I should make the 
isReal = true, in the code you give?

**Comment by Shin-NiL** [comment]
Nope, just in your gdscript or on your AdMob node properties.

**Comment by jingMV** [comment]
> 
> 
> Nope, just in your gdscript or on your AdMob node properties.

The ads is working now on my apps, but theirs a test ads text on it. how to remove that?

**Comment by Shin-NiL** [comment]
Did you set `is_real` to `true` and export the apk in release mode?

**Comment by jingMV** [comment]
> Did you set `is_real` to `true` and export the apk in release m

yes mate, I've set the is_real to true, 
And already in the playstore

**Comment by hideckies** [comment]
Excuse me for cutting in.

I hava the same problem with rewarded video in my game.

■my enviroment■
Godot version: 3.2.2
AdMob plugin version: 4.1.1

■already checked■
・Add my App ID to AndroidManifest.xml
・Set `is_real` to true
・Set my Ad Unit ID to `rewarded_id`
・Uncheck `Export with Debug` when exporting


I don't know what's causing it...

**Comment by hideckies** [comment]
I solved it by checking `Is Real` to true in the Inspector (NOT gdscript).

This is probably reflected at build time, so I think we need to set it to `true` in the Inspector beforehand.

**Comment by jingMV** [comment]
> 
> 
> I solved it by checking `Is Real` to true in the Inspector (NOT gdscript).
> 
> This is probably reflected at build time, so I think we need to set it to `true` in the Inspector beforehand.

hi mate, can u screenshot to me? all the step u do? thank you mate

**Comment by hideckies** [comment]
Sure! In my case,

## Before
I only set `is_real` to `true` in my code like this↓

![code](https://user-images.githubusercontent.com/52585124/96865948-92cd0080-14a5-11eb-81b5-24b880cd2ab7.png)


and did not check in the inspector↓

![before_inspector](https://user-images.githubusercontent.com/52585124/96863633-1dabfc00-14a2-11eb-9cbc-2abdaa61343f.png)

<br />

# After

I checked in the inspector↓

![after_inspector](https://user-images.githubusercontent.com/52585124/96863649-269ccd80-14a2-11eb-8edb-32f6d52092b1.png)

After that, I just exported it as release mode.

I hope it helps.

**Comment by jingMV** [comment]
> 
> 
> Sure! In my case,
> ## Before
> 
> I only set `is_real` to `true` in my code like this↓
> 
> ![code](https://user-images.githubusercontent.com/52585124/96865948-92cd0080-14a5-11eb-81b5-24b880cd2ab7.png)
> 
> and did not check in the inspector↓
> 
> ![before_inspector](https://user-images.githubusercontent.com/52585124/96863633-1dabfc00-14a2-11eb-9cbc-2abdaa61343f.png)
> 
> # After
> 
> I checked in the inspector↓
> 
> ![after_inspector](https://user-images.githubusercontent.com/52585124/96863649-269ccd80-14a2-11eb-8edb-32f6d52092b1.png)
> 
> After that, I just exported it as release mode.
> 
> I hope it helps.

Hi mate is not working on me
here is my screenshot
![222](https://user-images.githubusercontent.com/50164103/96959493-6b6c4700-152a-11eb-9c0a-30dc444e9af9.png)

![1](https://user-images.githubusercontent.com/50164103/96959487-64ddcf80-152a-11eb-8633-3b163b2037a2.png)

**Comment by hideckies** [comment]
> Hi mate is not working on me

"Test AD" is still displayed? Or the ad itself is not displayed?

**Comment by jingMV** [comment]
> 
> 
> > Hi mate is not working on me
> 
> "Test AD" is still displayed? Or the ad itself is not displayed?

test ad labels still display on the top of the ads

**Comment by hideckies** [comment]
> > > Hi mate is not working on me
> > 
> > 
> > "Test AD" is still displayed? Or the ad itself is not displayed?
> 
> test ad labels still display on the top of the ads

Is not your device added as a test device in the admod settings? ->　[https://apps.admob.com](https://apps.admob.com)

**Comment by jingMV** [comment]
> 
> 
> > > > Hi mate is not working on me
> > > 
> > > 
> > > "Test AD" is still displayed? Or the ad itself is not displayed?
> > 
> > 
> > test ad labels still display on the top of the ads
> 
> Is not your device added as a test device in the admod settings? ->　https://apps.admob.com

yes mate, I did not add my device as a test device on admob

**Comment by jingMV** [comment]
> 
> 
> > > > > Hi mate is not working on me
> > > > 
> > > > 
> > > > "Test AD" is still displayed? Or the ad itself is not displayed?
> > > 
> > > 
> > > test ad labels still display on the top of the ads
> > 
> > 
> > Is not your device added as a test device in the admod settings? ->　https://apps.admob.com
> 
> yes mate, I did not add my device as a test device on admob

I should try to create to admob account?

**Comment by hideckies** [comment]
> > > > > > Hi mate is not working on me
> > > > > 
> > > > > 
> > > > > "Test AD" is still displayed? Or the ad itself is not displayed?
> > > > 
> > > > 
> > > > test ad labels still display on the top of the ads
> > > 
> > > 
> > > Is not your device added as a test device in the admod settings? ->　https://apps.admob.com
> > 
> > 
> > yes mate, I did not add my device as a test device on admob
> 
> I should try to create to new admob account?

Umm... I have no idea at the moment, sorry...

**Comment by jingMV** [comment]
> 
> 
> > > > > > > Hi mate is not working on me
> > > > > > 
> > > > > > 
> > > > > > "Test AD" is still displayed? Or the ad itself is not displayed?
> > > > > 
> > > > > 
> > > > > test ad labels still display on the top of the ads
> > > > 
> > > > 
> > > > Is not your device added as a test device in the admod settings? ->　https://apps.admob.com
> > > 
> > > 
> > > yes mate, I did not add my device as a test device on admob
> > 
> > 
> > I should try to create to new admob account?
> 
> Umm... I have no idea at the moment, sorry...

okay mate, thank you all guys
