### ISSUE TITLE
No ads showing on my apps

### ISSUE THREAD

**Issue by jingMV** [Shin-NiL/Godot-Android-Admob-Plugin#93]
**Godot version: 3.2.2**

**AdMob Plugin version: 4.1.1**

**Issue description:**

When i try the test ads id its work properly on my phone, But when i publish my apps and add my App ID, The problem is no adds showing now, what should i do mate tnx

**Comment by Shin-NiL** [comment]
Use _logcat_ via command line or with Android Studio to get some debugging information, including the returning error codes. If you're getting error code 3, one common mistake is forget to configure the [app-ads.txt](https://support.google.com/admob/answer/9363762).

**Comment by jingMV** [comment]
> 
> 
> Use _logcat_ via command line or with Android Studio to get some debugging information, including the returning error codes. If you're getting error code 3, one common mistake is forget to configure the [app-ads.txt](https://support.google.com/admob/answer/9363762).

okay mate tnx, i will try it

**Comment by jingMV** [comment]
> 
> 
> > Use _logcat_ via command line or with Android Studio to get some debugging information, including the returning error codes. If you're getting error code 3, one common mistake is forget to configure the [app-ads.txt](https://support.google.com/admob/answer/9363762).
> 
> okay mate tnx, i will try it

When i try logcut i got the error code: 3

**Comment by Shin-NiL** [comment]
With error code 3 there's nothing we can do here, sorry. Many different things can cause this error, try to google it.

**Comment by jingMV** [comment]
> 
> 
> With error code 3 there's nothing we can do here, sorry. Many different things can cause this error, try to google it.

Okay mate thank you

**Comment by albemala** [comment]
I was receiving the same error code 3, I solved the problem following this answer on SO: https://stackoverflow.com/a/57964366/3305693

TL;DR: 
- set is_real = true
- publish a release build of your app on the Google Play Store (you can publish it as Open testing / Beta)
- you should then start seeing real ads (make sure to install the app you just published from the store, not from a local APK)
