### ISSUE TITLE
Mediation support?

### ISSUE THREAD

**Issue by phaitonican** [Shin-NiL/Godot-Android-Admob-Plugin#97]
Does this plugin have Ad Mob Mediation support?
https://developers.google.com/admob/android/mediation/facebook
If not, would it be hard to implement?

**Comment by Shin-NiL** [comment]
For what I can see this plugin can support mediation, but you'll need to do the required changes by yourself.
For the Facebook example, you should apply steps 3 and 4 (from the above documentation) on the plugin code and then compile the `aar` file.

**Comment by phaitonican** [comment]
Ah its the `admob-plugin/build.gradle` file i need to change then? Ok I will test it out, thanks!

**Comment by Shin-NiL** [comment]
Don't forget to put the new dependency on the `GodotAdMob.gdap` file.

**Comment by HanouaJ** [comment]
Where to add the dependencies for the mediation ads libraries ? because the build.gradle file doesn't recognize the "implementation" when added inside "dependencies {}" when I add the line :

implementation 'com.google.ads.mediation:facebook:6.14.0.0'
