### ISSUE TITLE
sent to test device

### ISSUE THREAD

**Issue by jingMV** [Shin-NiL/Godot-Android-Admob-Plugin#99]
**Godot version: 3.2.2**

**AdMob Plugin version: 4,1,1**

**Issue description: I dont run any emulator or settestdevice ids**

here is the logcat from live apps
![line_1](https://user-images.githubusercontent.com/50164103/97824254-02d15700-1cee-11eb-949c-34ea728a420c.png)
![line_2](https://user-images.githubusercontent.com/50164103/97824260-0664de00-1cee-11eb-9afc-601981f027a1.png)
![line_3](https://user-images.githubusercontent.com/50164103/97824267-09f86500-1cee-11eb-8da1-10e301e63ef0.png)

**Comment by Shin-NiL** [comment]
Are you still getting test ads only?

**Comment by jingMV** [comment]
Yes mate,

**Comment by jingMV** [comment]
> 
> 
> Are you still getting test ads only?

Yes Mate

**Comment by Shin-NiL** [comment]
It's really strange because users are publishing theirs games using the same version with no issues. I have no clues there, sorry.

**Comment by jingMV** [comment]
> 
> 
> It's really strange because users are publishing theirs games using the same version with no issues. I have no clues there, sorry.

**Comment by jingMV** [comment]
> 
> 
> It's really strange because users are publishing theirs games using the same version with no issues. I have no clues there, sorry.

Okay mate, thank u

**Comment by jingMV** [comment]
> 
> 
> It's really strange because users are publishing theirs games using the same version with no issues. I have no clues there, sorry.

Hi, i try to use the 4.0.0 plugin, then i saw i duplicate the admob gd script from my other folders. Thank you

**Comment by Shin-NiL** [comment]
Nice to know, thanks for reporting.
